GovAlta/ui-components

LICENSE
Note that the copyright template in the license text is part of the appendix of the Apache 2.0 license and not the actual copyright notice for the files in the repository.
The appendix provides instructions on how to apply a copyright notice (NOTICE file in the repo), but this is not a requirement of applying the Apache 2.0 licence. It is a requirement for Apache foundation repositories under Apache 2.0. 
For this repository, don't worry about the copyright notices for now.
This reverts commit b6e90df8bbc6b863982fc9e844e95f03e7b6ed8e.
=> chore: revert license text copyright template text

libs/web-components/src/common/context-store.ts, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/dropdown/DropdownItem.svelte, libs/web-components/src/components/dropdown/types.ts, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/radio-group/RadioItem.svelte, libs/web-components/src/components/radio-group/types.ts
The previous attempt at having a context store subscription unsubscribe
from itself after the first callback is handled worked in tests, but
fell apart when outside the tests and storybook.
=> fix: context-store state issue

libs/styles/src/lib/vars.css, libs/web-components/src/components/button/Button.svelte
The previously use line-height resulted in a different overall height
due to the difference in border-width used between the different buttons
=> fix(#638): use height rather than line-height

libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte
https://github.com/GovAlta/ui-components/issues/720
Before
After
=> fix: prevent radio and checkboxes from getting squishing

Makefile, libs/web-components/demo/src/App.svelte, libs/web-components/src/components/icon-button/IconButton.svelte, libs/web-components/src/components/icon/Icon.svelte
There are a couple filed bugs on the ionic icons github for this issue.
To make things work on our side the pointer events are disabled on the
`ion-icon` component to allow our title to override it.
https://goa-dio.atlassian.net/browse/DDIDS-594
=> fix: show the user set title for the goa-icon and goa-icon-button

libs/docs/src/react-setup.stories.mdx, libs/react-components/package.json
For now the web component dependency will need to be added manually
until we release a 1.0 version
=> fix: remove web-component dependency from react lib

apps/angular-demo/src/app/input-component/input-component.component.html, apps/angular-demo/src/app/input-component/input-component.component.ts, apps/react-demo/src/routes/input.tsx, libs/docs/src/components/common/Input.stories.mdx
Also updated the angular demo to include values in the input boxes. And updated the react demo to have seconds in one of the time inputs
=> fix(DDI-969): Adding more examples of datetime input in stories

apps/angular-demo/src/app/container/container.component.html, libs/docs/src/components/common/Container.stories.mdx, libs/docs/src/components/common/OneColumLayout.stories.mdx, libs/docs/src/components/common/TwoColumnLayout.stories.mdx, libs/react-components/src/lib/container/container.spec.tsx, libs/react-components/src/lib/container/container.tsx, libs/web-components/src/components/container/Container.svelte, libs/web-components/src/components/container/ContainerWrapper.test.svelte
Made sure that the basic container had no accent bar. Changed default container to basic container.
Added title to the properties tabs
Modified headingSize to accentBar.
Modified colored to backgroundColour.
Also updated the figma link in the one-column and two-column layout pages.
=> fix(DDI-960): Modified the container storybook page

libs/docs/src/components/goa/AppFooter.stories.mdx, libs/docs/src/components/goa/app-header.stories.mdx, libs/styles/src/lib/vars.css, libs/web-components/src/components/app-header/AppHeader.svelte, libs/web-components/src/components/footer/Footer.svelte, libs/web-components/src/components/modal/Modal.svelte, libs/web-components/src/layouts/two-column-layout/TwoColumnLayout.svelte
Modified both the AppHeader and AppFooter stories to include the actual measurements for a property. Increased the max width in the CSS that's used for both AppHeader and AppFooter. Modified width of AppFooter to 100% of the container, instead of 100% of viewport. Removed a console onMount message for Modals.
=> fix: Modify padding for AppHeader

.github/workflows/alpha-release-ci.yml, .github/workflows/prod-release-ci.yml
It looks like the deployment is happening before the actual build finishes. This should fix that.
=> fix(DDI-1015): Added a wait command to the start-build

workspace.json
This is being done to release angular-components properly
=> fix: Modified workspace.json to properly run the release command

apps/angular-demo/src/app/dropdown/dropdown.component.html, apps/angular-demo/src/app/input-component/input-component.component.html, apps/react-demo/src/routes/input.tsx, libs/web-components/src/components/input/Input.svelte
Updated the borders on the prefix and suffix of input components to be properly greyed out if the input is disabled.
Updated the angular and react demo to have this setup for testing purposes.
Also updated the dropdown component in the angular demo to be more inline with the storybook.
=> fix(DDI-1122): Updated borders on prefix and suffix

libs/web-components/src/components/input/Input.svelte, libs/web-components/src/components/text-area/TextArea.svelte
This was done so it would use the natural color for the HTML component, including when it was disabled.
=> fix(DDI-1123): Removed background-color from textarea component

libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
Currently the Microsite header is not inline with the design component created. The badge inside the header (Alpha, Beta, etc…) has too much padding on the top and the bottom. And the Microsite Header itself has too much padding on the top and the bottom.
Badge inside the Microsite Header has top and bottom padding reduced to 2px.
Microsite Header has padding reduced to 4px
Screenshots:
**Angular**
**React**
=> feat/DDI-1120: Adjust padding for Microsite Header

libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte
* The aria label for the custom dropdown element wasn't being set correctly on the native <input> element within the shadow dom.
* Instead, it was being set on the host goa-input element
* This was tipping off the NVDA screen reader while it worked fine on other screen reader
* pass along the ariaLabel prop to <goa-input> and let that set the aria-lable on the native input element
=> [DDIDS-1141] Fix aria-label readout for Dropdown elements

libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/input/Input.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte
* *AC* on the ticket requires to set the background color on the input element but doing so causes some amount of the background color bleeding out of the container. The PR now sets the background color on the `goa-input` container. 
* With this approach, the base level `line-height` seems to be breaking the input styles when leading and trailing content are present. The PR also overrides this line-height style on `goa-input`
[DDIDS-1167]: https://goa-dio.atlassian.net/browse/DDIDS-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DDIDS-1167] Fix input background color

libs/web-components/src/components/footer/Footer.svelte
This PR is just to change optional chaining `?.` to more old approach to make web-components bundle work with Vue v2
=> chore: change nullable object check approach

libs/web-components/src/components/text-area/TextArea.svelte
* Use css `resize` property
* Seems to be supported on most browsers https://caniuse.com/css-resize. ios-Safari being an exception as there is no resize gesture on ios interface. Meaning on ios-safari both verical and horizontal drag is disabled
=> bug(DDIDS-1203): Textarea no horizontal resizing

apps/angular-demo/src/app/table/table.html, apps/react-demo/src/routes/table.tsx, libs/docs/src/components/common/Table.stories.mdx, libs/react-components/src/lib/notification/notification.spec.tsx, libs/web-components/package-lock.json, libs/web-components/package.json, libs/web-components/rollup.config.js, libs/web-components/src/components/table/Table.svelte, libs/web-components/svelte.build.config.js, package-lock.json, package.json, workspace.json
https://goa-dio.atlassian.net/browse/DDIDS-1152
https://goa-dio.atlassian.net/browse/DDIDS-1213
* Added a new package to support the use of `:global` with svelte custom components. [Details](https://github.com/sveltejs/svelte/issues/2969#issuecomment-894511663)
* - [x] ~~Will update the storybook docs once https://github.com/GovAlta/ui-components/pull/1025/ is merged~~
=> feat(DDIDS-1152, DDIDS-1213): Table component number column styling

libs/angular-components/README.md
This is being done mainly to force NPM to update to a new angular components release so that we can get updated documentation on NPM.
This has a side effect that I don't believe the `-f` is actually necessary
=> fix: Just to force a new release for angular components

libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte
Check (holding action) on the radio checkbox and the checkbox, doesn't display a yellow border. This PR is to fix it.  
Task: https://goa-dio.atlassian.net/browse/DDIDS-1237
https://user-images.githubusercontent.com/120135417/221998533-8aacdcff-824a-4669-b98b-93d1f6ce2358.mov
=> fix(DDI-1237): safari-focus-state for checkbox and radio

libs/react-components/src/lib/table/table.tsx
Passing variant prop from React GoATable to the web component.
=> fix(DDI-1241): pass variant prop from react

libs/web-components/src/components/table/Table.svelte
If you try to implement dynamic headers with goa-table, and then try to use goa-table-sort-header with those dynamic headers, sorting won’t work, but only in Angular v15, it works fine in v12 (did not test with v13 or v14).
Step 1: Create your Angular project from https://github.com/GovAlta/ui-components-angular-template
Step 2: Add your table code: https://github.com/vanessatran-ddi/angular-ui-component-sample/blob/main/src/app/home/home.component.html#L7
Step 3: Add code under component ts like: https://github.com/vanessatran-ddi/angular-ui-component-sample/blob/main/src/app/home/home.component.ts#L14
Step 4: Change the path of this repo local dist folder https://github.com/vanessatran-ddi/angular-ui-component-sample/blob/main/package.json#L14
Step 5: Run the angular application …
=> fix(DDI-1268): fix table sort header doesn't work with angular 15

libs/react-components/src/lib/accordion/accordion.tsx, libs/react-components/src/lib/container/container.tsx, libs/web-components/src/components/accordion/Accordion.svelte, libs/web-components/src/components/container/Container.svelte, libs/web-components/src/components/details/Details.svelte
Set margin-bottom to 0 of the last <p> tag from Accordion, Container, and Details components.
=> fix(DDI-1269): remove margin-bottom of last <p> tag

libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/pagination/Pagination.svelte, libs/web-components/src/components/pagination/pagination.spec.ts
There is no error if you type in a page that doesn't exist (Pagination Component)
AC: Change the page selection component to a dropdown
- [DDIDS-1266](https://goa-dio.atlassian.net/browse/DDIDS-1266)
For React app:
https://user-images.githubusercontent.com/120135417/227081765-4c49b3da-a432-47bc-9ecc-3f0e25d896ec.mov
For Angular app:
https://user-images.githubusercontent.com/120135417/227081792-8ad3f928-c002-444b-8bf2-f47869ec32de.mov
[DDIDS-1266]: https://goa-dio.atlassian.net/browse/DDIDS-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DDI-1266): change current page number from input text to dropdown

libs/web-components/src/components/input/Input.svelte
If leading or trailing content slots exists, then interaction states will be shown only on input box.
=> feat(DDI-1273): added interaction states on input

.gitignore, libs/web-components/playground/src/App.svelte.template
Adds a svelte template file that allows a dev to copy to local env and make changes in it without having to worry about accidentally including changes in PRs
=> chore: create playground template

apps/angular-demo/src/app/detail/detail.html, apps/angular-demo/src/app/detail/detail.ts, apps/react-demo/src/app/app.tsx, apps/react-demo/src/main.tsx, apps/react-demo/src/routes/details.tsx, libs/docs/src/components/common/Details.stories.mdx, libs/react-components/src/lib/details/details.spec.tsx, libs/react-components/src/lib/details/details.tsx, libs/web-components/src/components/details/Details.html-data.json, libs/web-components/src/components/details/Details.svelte, libs/web-components/src/components/details/details.spec.ts, libs/web-components/src/components/details/doc.md
End users want to expand the additional information programmatically. This PR is to add a boolean attribute "open" that allows web component GoADetails expanded/hidden programmatically. 
[DDI-1328](https://goa-dio.atlassian.net/browse/DDIDS-1328)
- Add boolean "open"  to web component GoADetails
- Update React wrapper 
- Add storybook
- Update VS Code data.
=> feat(DDI-1328): Allow details component expand programmatically

libs/docs/src/components/common/Button.stories.mdx, libs/web-components/src/components/button/Button.svelte
There is no easy fix for this. 
For now, 
* making sure that the native button gets the `type=submit` prop
* updating the docs
=> chore(#1284): Update docs about button type=submit

apps/react-demo/src/routes/formItem.tsx, libs/react-components/src/lib/form/form-item.tsx
Remove the required label for GoaFormItem
=> fix(#1331): GoAFormItem(React) should not require label property

libs/react-components/src/lib/table/table.spec.tsx, libs/react-components/src/lib/table/table.tsx, libs/web-components/src/components/table/Table.svelte
* Couldn't add a test case to validate the `_sort` event firing, as the `goa-table-sort-header` is within a slot and was hard to test with`@testing-library/svelte`. Open to suggestions on this
* Added a small test case on the react component but that isn't the actual the issue
=> fix(#1327) Fix table sorting

.releaserc.json
Commits to `BUGFIX` branch do not get published to the latest distribution tag on npm. Rather the [new version](https://www.npmjs.com/package/@abgov/react-components?activeTab=versions) gets published under the `BUGFIX` dist. 
Update semantic release configuration to publish to latest tag. 
Docs for this configuration change can be found [here](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#channel)
Will need to push a bugfix to test this
=> chore: Update configuration for bugfix branch to publish under latest tag

libs/web-components/src/components/pagination/Pagination.svelte
This should make the Pagination page select dropdown autosize, which should mean that 2 character numbers should fit now.
=> fix(#1360): Removed width from Pagination dropdown

libs/react-components/src/lib/textarea/textarea.tsx
It follows up and unblocks the PR https://github.com/GovAlta/ui-components-docs/pull/42
With the logic of the Sandbox, if we use the React name as `GoATextArea`, The Angular code snippet will be `goa-text-area`. 
This PR is to add another name for Text Area component, which is `GoATextarea`, which helps generate the code in Angular correctly. 
After the change:
=> chore: Add another name for GoATextArea vs GoATextarea.

libs/web-components/playground/src/pg-dropdown.svelte, libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/popover/Popover.svelte
To test
```html
<goa-dropdown on:_change={(e) => setValue(e)} value={value} disabled={false} leadingicon="airplane" width="100%">
<goa-dropdown-item value="red" label="red"></goa-dropdown-item>
<goa-dropdown-item value="blue" label="blue"></goa-dropdown-item>
</goa-dropdown>
<goa-dropdown on:_change={(e) => setValue(e)} value={value} disabled={false} leadingicon="airplane" width="80%">
<goa-dropdown-item value="red" label="red"></goa-dropdown-item>
<goa-dropdown-item value="blue" label="blue"></goa-dropdown-item>
</goa-dropdown>
<goa-dropdown on:_change={(e) => setValue(e)} value={value} disabled={false} leadingicon="airplane">
<goa-dropdown-item value="red" label="red"></goa-dropdown-item>
<goa-dropdown-item value="blue" label="blue"></goa-dropdown-item>
</goa-dropdown>
```
[Peek …
=> fix(#1496): properly calculate dropdown percent widths

libs/web-components/playground/src/pg-tabs.svelte, libs/web-components/src/components/tabs/Tabs.svelte
It shouldn't move to the new tab if the focus element isn't a tab button.
https://github.com/GovAlta/ui-components/assets/120135417/d9e63a94-c25d-43d3-b992-0ccd169628f4
=> fix(#1476): not change current tab if it isn't focus

libs/angular-components/src/lib/value-directive.ts
Allow angular input resetValue,patchValue or setValue and visually clear the input text value. 
Video as below: 
https://github.com/GovAlta/ui-components/assets/120135417/a4af4bf0-5d00-48c8-8211-39e25521c6f7
With the code snippet: 
```
export class FormItemComponent {
formGroup = new FormGroup({
txtRequesterName: new FormControl(),
})
constructor() {}
searchRequesterClickIcon () {
console.log("Current value ", this.formGroup.get("txtRequesterName")?.value);
this.formGroup.get("txtRequesterName")?.patchValue("");
console.log("New value ", this.formGroup.get("txtRequesterName")?.value);
}
}
<goa-form-item [formGroup]="formGroup">
<goa-input goaValue
placeholder="Search requester"
formControlName="txtRequesterName"
trailingicon="close"
[handletrailingiconclick]="true" …
```
=> fix(#1598): angular visually empty form control value by directive - needs review

libs/web-components/src/components/text-area/TextArea.spec.ts, libs/web-components/src/components/text-area/TextArea.svelte
Fix issue https://github.com/GovAlta/ui-components/issues/1597
Screenshots: 
React works with onChange, and with counter
Angular works  and with counter
=> fix(#1597): textarea not calling 'change' callback on keypress - needs review

libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte
In scenarios where dropdown width is set to be more than the parent container the dropdown should respect the parent container width. This applies when there isn't enough screen real-estate. 
The videos show how the below piece of React code is rendered before and after this change
```jsx
<GoADropdown name="colors" value={"red"} onChange={onChange} width="700px">
<GoADropdownItem value="red" label="Red" />
<GoADropdownItem value="green" label="Green" />
<GoADropdownItem value="blue" label="Blue" />
</GoADropdown>
```
The issue still persists when the screen size is changed. This only computes the parent container width on initial render. 
https://github.com/GovAlta/ui-components/assets/119442489/84a1bc1c-6d40-4dba-ae71-2247e350fd33 …
=> fix(#1496): Restrict dropdown width to parent container - code review needed

libs/web-components/src/assets/css/components.css, libs/web-components/src/components/table/TableSortHeader.svelte
extend our current class `goa-table-number-column` to be able to apply it to headers
This wasn't working only when a `tableSortHeader` is used within a `th` element.
```jsx
<th className="goa-table-number-column">
<GoATableSortHeader name="age" direction="asc">
Age
</GoATableSortHeader>
</th>
```
this should now align the table header element to the right
=> fix(#1492) : Table - Adjust styling for number table header - code review needed

libs/web-components/src/components/dropdown/Dropdown.svelte
This seemed to be an angular issue only when changing routes from a page that contained a dropdown component.
The error was due to the Dropdown component responding to the `slotchanged` event, which made reference to one of the elements within the page. However, by the time the reference was made the html element had been removed from the DOM; resulting in the null exception.
=> fix(#1679): null querySelector errors in dropdown

.env, libs/react-components/src/index.ts
The web-components library needs to be imported for production releaase, but the import prevent live reloads when running in a dev environment.
The previous attempt at the work-around caused breaking builds; reversing the bool conditions should fix the issue.
=> fix: react import for production build

libs/web-components/src/components/dropdown/Dropdown.svelte
Issue described: https://github.com/GovAlta/ui-components/issues/1510 
I tested with Chrome. You can set the contacts as the below:
The code I referred to can be found here: 
https://stackblitz.com/edit/b1due8?file=src%2Fapp%2Fapp.component.html
**Notice**: In order to test it, you must use the code in an angular app that doesn't navigate by router. (Our playground example app.component.html) is a good place to start. 
https://github.com/GovAlta/ui-components/assets/120135417/c95e600d-7768-4163-b528-81ed4f3b4a61
=> fix(#1510): dispatch value filterable dropdown when browser autofil

libs/web-components/src/components/input/Input.svelte
Continue from #1635 
Tested with the below cases:
* trailing, leading, and both
* trailing, leading and both under error case
* disabled
* no trailing, no leading
* goa-input used under dropdown, focus border remains the same.
https://github.com/GovAlta/ui-components/assets/120135417/ca0d96b2-2025-4e69-bba5-96b6e052f5f0
=>  1577: textfield border renderring on error and focus

libs/web-components/src/components/tabs/Tabs.svelte, libs/web-components/src/components/tabs/tabs.spec.ts
Hash urls will allow the url to change when the tab is chaned, allowing for `popstate` events to be handled for any page updates required. At a later time this will also allow the tab's `open` status to be set if a url with one of hashes is opened directly.
To test this, if the previous Tab tests function as they did before then it is all good.
=> fix: tabs are now links instead of buttons

libs/web-components/src/components/app-header-menu/AppHeaderMenu.svelte, libs/web-components/src/components/app-header-menu/AppHeaderMenuWrapper.test.svelte, libs/web-components/src/components/app-header-menu/app-header-menu.spec.ts
Fixing #1676 
https://github.com/GovAlta/ui-components/assets/120135417/3f4d70e3-8305-47fe-a199-6ec6a4a72659
Angular code: 
```
<goa-app-header url="https://example.com" heading="Ticket and Fine Payments">
<a href="#">Support</a>
<goa-app-header-menu heading="Tickets" leadingIcon="ticket">
<a href="#" (click)="selectMenu('Cases'); $event.preventDefault()">Cases</a>
<a href="#" (click)="selectMenu('Payments'); $event.preventDefault()">Payments</a>
<a href="#" (click)="selectMenu('Outstanding');$event.preventDefault()">Outstanding</a>
<a href="#">Test</a>
</goa-app-header-menu>
<a href="#" class="interactive">Sign in</a>
</goa-app-header>
<span>Selected Menu: {{selectedMenu}}</span>
```
```
@Component({
selector: "abgov-app-header",
templateUrl: …
```
=> fix(#1676): app-header menu should close after menu item is clicked

libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
Fixing #1718 
Code example in Angular:
```
<goa-microsite-header
type="alpha"
level="alpha"
version="UAT"
maxcontentwidth="1400px"
></goa-microsite-header>
```
=> fix(#1718): microsite header background color be fullwidth

libs/web-components/src/components/container/Container.svelte
https://github.com/GovAlta/ui-components/issues/1739
Before:
With fix:
Code to replicate issue and see fix.
```
import { GoAContainer, GoADropdown, GoADropdownItem, GoAFormItem } from "@abgov/react-components";
export function Bug1739Page() {
return <>
<p>
Popover within dropdown would appear underneath the following GoAContainer component only if
the popover was also within a GoAContainer
<a href="https://github.com/orgs/GovAlta/projects/35/views/1?filterQuery=assignee%3Achrisolsen&pane=issue&itemId=58028866">Link to issue</a>
</p>  
<GoAContainer>
<GoAFormItem label="Basic dropdown">
<GoADropdown name="item" onChange={() => {}} relative={true}>
<GoADropdownItem value="red" label="Red"></GoADropdownItem>
<GoADropdownItem value="green" label="Green"></GoADropdownItem>
<GoADropdownItem …
```
=> fix(#1739): prevent popovers from appearing underneatch goa-container sibling components

libs/web-components/src/components/container/Container.svelte
=> fix: replace no longer used @container query with @media

libs/react-components/vite.config.ts
The build .js file is needed for unit tests
=> fix: re-add the cjs build for react

libs/web-components/src/components/accordion/Accordion.svelte
This PR is a proposed fix for https://github.com/GovAlta/ui-components/issues/1592. It hides the secondary text element in the accordion header if the `secondaryText` property is empty.
Without any secondary text:
With secondary text:
- **2. Make sure that you've checked the boxes below before you submit MR:**
When review is satisfactory reviewer will merge the changes.
=> fix(#1592): Hide accordion secondary text if property is empty

libs/web-components/src/components/container/Container.svelte
This change allows a container with a thick heading to accommodate multi-line titles. It includes the following changes:
- Removes `max-height` from the thick heading
- Only renders `title` and `actions` slots if the slots are available. This avoids extra padding.
- Uses `flexbox` with a column gap for the `actions` slot to match the Figma component.
- Uses `--goa-typography-heading-s` for the heading title (see [comment](https://github.com/GovAlta/ui-components/issues/1607#issuecomment-1933540539)).
- Replaces `rem` values with design tokens.
**2. Make sure that you've checked the boxes below before you submit MR:**
**3. Which issue and JIRA item does this PR fix (optional)**
**4. Additional notes for the reviewer**
When review is satisfactory reviewer …
=> fix(#1607): remove max height from container with thick heading

libs/web-components/src/components/checkbox/Checkbox.svelte
This PR addresses a couple minor layout issues on the checkbox, including...
- Vertically aligns the text with the checkbox
- Sets the text line height to `--goa-line-height-3` to better align with the Figma component
- Replaces `rem` values with design tokens
- **2. Make sure that you've checked the boxes below before you submit MR:**
**3. Which issue and JIRA item does this PR fix (optional)**
**4. Additional notes for the reviewer**
When review is satisfactory reviewer will merge the changes.
=> fix(#1768): adjust checkbox label alignment

libs/web-components/src/components/tooltip/Tooltip.svelte
This code fixes https://github.com/GovAlta/ui-components/issues/1522 by increasing the z-index of the `tooltip` component.
In comparison, the input and dropdown components both have a z-index of `1`:
https://github.com/GovAlta/ui-components/blob/e59da1a6b5ec041339c746a90b4b0ca6254ef417/libs/web-components/src/components/input/Input.svelte#L357
https://github.com/GovAlta/ui-components/blob/e59da1a6b5ec041339c746a90b4b0ca6254ef417/libs/web-components/src/components/dropdown/Dropdown.svelte#L794
The stepper component has elements with z-index of `1` and `2`:
https://github.com/GovAlta/ui-components/blob/e59da1a6b5ec041339c746a90b4b0ca6254ef417/libs/web-components/src/components/form-stepper/FormStepper.svelte#L183 …
=> fix(#1522): increase tooltip z-index so it renders above dropdown

libs/web-components/src/components/text-area/TextArea.svelte
- Adds the `--width` custom property width to `.root`
- Adds a `100%` fallback to the other width custom properties in the component
- **2. Make sure that you've checked the boxes below before you submit MR:**
When review is satisfactory reviewer will merge the changes.
=> fix(#1697): use width custom property for textarea root

libs/react-components/src/lib/date-picker/date-picker.spec.tsx, libs/react-components/src/lib/date-picker/date-picker.tsx, libs/web-components/src/components/date-picker/DatePicker.svelte, libs/web-components/src/components/date-picker/date-picker.spec.ts
This PR is a fix for https://github.com/GovAlta/ui-components/issues/1645 that adds an `error` property to the date picker.
- **2. Make sure that you've checked the boxes below before you submit MR:**
**3. Which issue and JIRA item does this PR fix (optional)**
**4. Additional notes for the reviewer**
When review is satisfactory reviewer will merge the changes.
=> fix(#1645): add error property to date picker

libs/web-components/src/assets/css/components.css, libs/web-components/src/components/table/Table.svelte
Instead of using JS for dom manipulation and adding 'relaxed' class to all eligible tds, the customElement <goa-table> is forced to spit out 'variant' attribute, and then the css selector goa-table[variant='relaxed'] td does work. See Chris' last comment below
=> fix(#1466): apply padding when variant=relaxed

libs/web-components/src/components/table/Table.svelte
Allow table to have scrolling bar 
Testing code: 
```
<div style="background-color: red; width:200px">
<goa-table mb="xl" (_sort)="handleSort($event)">
<thead>
<tr>
<th>
<goa-table-sort-header name="firstName"
>First name and really long header</goa-table-sort-header
>
</th>
<th>
<goa-table-sort-header name="lastName">Last name</goa-table-sort-header>
</th>
<th>
Age
</th>
<th class="goa-table-number-header">
Age
</th>
<th>
Age
</th>
<th>
Age
</th>
<th>
Age
</th>
<th>
Age
</th>
</tr>
</thead>
<tbody>
<tr *ngFor="let user of users; index as i">
<td>{{ user.firstName }}</td>
<td>{{ user.lastName }}</td>
<td class="goa-table-number-column">{{ user.age }}</td>
<td class="goa-table-number-column">{{ user.age }}</td>
<td class="goa-table-number-column">{{ user.age }}</td>
<td …
```
=> fix(#1461): table overflow-x should be auto

libs/react-components/src/lib/app-header-menu/app-header-menu.spec.tsx, libs/react-components/src/lib/app-header-menu/app-header-menu.tsx, libs/react-components/src/lib/calendar/calendar.spec.tsx, libs/react-components/src/lib/calendar/calendar.tsx, libs/react-components/src/lib/date-picker/date-picker.spec.tsx, libs/react-components/src/lib/date-picker/date-picker.tsx, libs/react-components/src/lib/details/details.spec.tsx, libs/react-components/src/lib/details/details.tsx, libs/react-components/src/lib/file-upload-card/file-upload-card.spec.tsx, libs/react-components/src/lib/file-upload-card/file-upload-card.tsx, libs/react-components/src/lib/file-upload-input/file-upload-input.spec.tsx, libs/react-components/src/lib/file-upload-input/file-upload-input.tsx, libs/react-components/src/lib/footer-meta-section/footer-meta-section.spec.tsx, libs/react-components/src/lib/footer-meta-section/footer-meta-section.tsx, libs/react-components/src/lib/side-menu-group/side-menu-group.spec.tsx, libs/react-components/src/lib/side-menu-group/side-menu-group.tsx, libs/react-components/src/lib/side-menu-heading/side-menu-heading.spec.tsx, libs/react-components/src/lib/side-menu-heading/side-menu-heading.tsx, libs/react-components/src/lib/side-menu/side-menu.spec.tsx, libs/react-components/src/lib/side-menu/side-menu.tsx, libs/react-components/src/lib/tabs/tabs.spec.tsx, libs/react-components/src/lib/tabs/tabs.tsx
This change addresses  https://github.com/GovAlta/ui-components/issues/1593 by adding a `testId` property to the following React components: 
- <del>Accordion</del> (I removed it because it is a [breaking change](https://github.com/GovAlta/ui-components/pull/1800#discussion_r1580034789))
- AppHeaderMenu
- Calendar
- DatePicker
- Details
- FileUploadCard
- FileUploadInput
- FooterMetaSection
- SideMenu
- SideMenuGroup
- SideMenuHeading
- Tabs
**2. Make sure that you've checked the boxes below before you submit MR:**
=> fix(#1593): add testId attribute to react components

libs/web-components/src/components/form-item/FormItem.svelte
This PR addresses https://github.com/GovAlta/ui-components/issues/1796 with the following changes:
- Adds extra spacing between a large label and the input
- Uses the proper font values for the error message
- Vertically aligns the error icon with the new line height using a transform
- Replaces other spacing values in the `FormItem` component with design tokens
Tasks:
=> fix(#1796): update form item spacing and font

libs/web-components/src/components/modal/Modal.svelte
This PR fixes https://github.com/GovAlta/ui-components/issues/1407. It subtracts the height of the actions section from the max height of the modal scroll area. This lets a modal with actions fit vertically in a mobile viewport.
Modal has correct max height on mobile when...
=> fix(#1407): reduce max modal height when actions exist

libs/web-components/src/components/radio-group/RadioGroup.svelte
Remove `disabled` attribute from `input` that is rendered even the value is false.
https://github.com/GovAlta/ui-components/assets/120135417/3d7e808a-4174-453e-93a7-a0954757d1d0
=> fix(#1837): radio doesn't work on mac and chrome browser

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
Create a Drag and Drop variant of the File Upload. Make sure you can select multiple files using it, while using the file select window (not dragging and dropping).
=> fix(#1818): Adding multiple back to File Upload

libs/react-components/src/lib/icon-button/icon-button.spec.tsx, libs/react-components/src/lib/icon-button/icon-button.tsx, libs/web-components/src/components/icon-button/IconButton.spec.ts, libs/web-components/src/components/icon-button/IconButton.svelte
This PR addresses https://github.com/GovAlta/ui-components/issues/1146 with the following changes:
- Adds `light` variant
- Updates colours for other variants from the [Figma design](https://www.figma.com/file/jDsIoiKh5ViZRWJdS0Dgtf/Component---Button?type=design&node-id=2403%3A133290&mode=design&t=YCaqJONkIYZ8AFc8-1)
- Uses `dark` styling for `nocolor`
- Uses `light` styling for `inverted`
- Adds transition animation to all variants, not just `color` and `dark`
- Adds console warnings that `nocolor` and `inverted` are deprecated
**PR checklist**
=> fix(#1146): update icon button variants

libs/web-components/src/common/utils.ts, libs/web-components/src/components/accordion/AccordionWithHeadingContentWrapper.test.svelte, libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/dropdown/DropdownItem.svelte, libs/web-components/src/components/dropdown/DropdownWrapper.test.svelte, libs/web-components/src/components/file-upload-input/FileUploadInput.svelte, libs/web-components/src/components/file-upload-input/file-upload-input.spec.ts, libs/web-components/src/components/focus-trap/FocusTrap.spec.ts, libs/web-components/src/components/footer/Footer.svelte, libs/web-components/src/components/form-step/FormStep.svelte, libs/web-components/src/components/form-step/form-step.spec.ts, libs/web-components/src/components/form-stepper/FormStepper.svelte, libs/web-components/src/components/form-stepper/FormStepperWrapper.test.svelte, libs/web-components/src/components/form-stepper/form-stepper.spec.ts, libs/web-components/src/components/modal/Modal.svelte, libs/web-components/src/components/pages/Pages.svelte, libs/web-components/src/components/popover/Popover.svelte, libs/web-components/src/components/radio-group/RadioGroup.spec.ts, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/radio-item/RadioItem.svelte, libs/web-components/src/components/tab/Tab.svelte, libs/web-components/src/components/tabs/Tabs.svelte, libs/web-components/src/components/tabs/TabsWrapper.test.svelte, libs/web-components/src/components/tabs/tabs.spec.ts
Some refactors were done on the following, so they need some quick tests.
The parent/child changes that were made require more extensive testing for the following components:
=> fix: use events for web-component parent/child communication

libs/react-components/src/lib/container/container.spec.tsx, libs/react-components/src/lib/container/container.tsx, libs/web-components/src/components/container/Container.spec.ts, libs/web-components/src/components/container/Container.svelte
This PR for https://github.com/GovAlta/ui-components/issues/1816 adds a width property to the Container component. It has two values:
| Name | Description | Screenshot |
|--------|--------|--------|
| Full | Expand to fit available horizontal width (default) | <img width="529" alt="image" src="https://github.com/GovAlta/ui-components/assets/1479091/e8605794-1546-46b8-bf9a-375b291b25c1"> |
| Content| Shrink to width of content. | <img width="525" alt="image" src="https://github.com/GovAlta/ui-components/assets/1479091/88eec10d-8967-4d29-b163-00a066d9b51f"> |
=> feat(#1816): width property for container

libs/react-components/src/lib/form-item/form-item.tsx
GoAFormItemProps also need to be updated...in the form-item.tsx
```
error?: React.ReactNode;
helpText?: React.ReactNode;
```
=> fix(#1814): allow form-item slotted content for helptext and error

libs/web-components/src/components/chip/Chip.svelte
=> fix(#1515): handle long text in chip

libs/web-components/src/components/checkbox/Checkbox.svelte
This PR address several issues with the checkbox component (https://github.com/GovAlta/ui-components/issues/1876, https://github.com/GovAlta/ui-components/issues/1856, https://github.com/GovAlta/ui-components/issues/1863, https://github.com/GovAlta/ui-components/issues/1771). It includes the following changes:
- Uses the following priority for setting `aria-label`:
1. `arialabel` property
2. `text` property
3. `name` property
4. nothing
- Aligns the checkbox to the top when the label wraps
- Replaces min height with bottom padding
- Replaces some `rem` spacing values with design tokens
- Multiple checkboxes vertically stack
- The clickable label is the width of the text, not the full width of the available space
Here's a comparison of the difference with the below example in playground: …
=> fix(#1876, #1856, #1863, #1771): checkbox aria label & layout fixes

libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/tab/Tab.svelte, libs/web-components/src/components/tabs/Tabs.svelte
Tabs within tabs (not normally done) would show the inner tabs in the outer tabs
Certain doc pages would show a blank tab
=> 1883 fix tabs

libs/web-components/src/common/utils.ts, libs/web-components/src/components/accordion/Accordion.spec.ts, libs/web-components/src/components/accordion/Accordion.svelte, libs/web-components/src/components/details/Details.svelte, libs/web-components/src/components/details/details.spec.ts
Ticket is https://github.com/GovAlta/ui-components/issues/1868
**Note: The AC "Body content in an accordion and detail components should be read by a screen reader when the Accordion is expanded" cannot be fulfilled because this is against what NVDA suggested.**
Reference: [Should Accordion Header expanding read Accordion Panel by default?](https://github.com/w3c/aria-practices/issues/1280)
What this ticket is doing:
* We will follow the standard practice at https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/
* Also the asking to fix is https://goa-dio.slack.com/archives/C02PLLT9HQ9/p1716488793498059 mentioned as they need `aria-label`, `aria-labelledby`
Screenshot:
=> fix(#1868): enhance accordion & details accessibility

libs/web-components/src/components/block/Block.svelte
allow `input` 100% inside `block`
Example code: 
```
<goa-block gap="xl" direction="column">
<goa-container>Test</goa-container>
<goa-form-item label="Phone number">
<goa-input width="100%" (_change)="onChange($event)" [value]="value" name="phone">
<div slot="leadingContent">
<goa-block direction="row" alignment="center" gap="none">
<goa-icon type="add" size="small"></goa-icon> <span class="medium-text">1</span>
</goa-block>
</div>
</goa-input>
</goa-block>
```
For the `ui-components-docs`:
Before fix: 
After fix:
=> fix(#1867): allow child element 100% width inside block

libs/react-components/src/lib/popover/popover.spec.tsx, libs/react-components/src/lib/popover/popover.tsx, libs/web-components/src/components/app-header-menu/AppHeaderMenu.svelte, libs/web-components/src/components/app-header-menu/app-header-menu.spec.ts, libs/web-components/src/components/popover/Popover.html-data.json, libs/web-components/src/components/popover/Popover.svelte, libs/web-components/src/components/popover/popover.spec.ts
=> fix(#1713): minwidth and maxwidth for app header menu

libs/web-components/src/components/tabs/Tabs.svelte
```
export default function Tabs() {
const [isReport, setIsReport] = useState(false);
function onClick() {
setIsReport(true);
}
return (
<>
<GoATabs>
<GoATab heading="1">Content 1</GoATab>
<GoATab heading="2">Content 2</GoATab>
<GoATab heading="3">Content 3</GoATab>
{isReport ? <GoATab heading="Report">Some Random Content</GoATab> : <></>}
</GoATabs>
<GoAButton onClick={onClick} mt="3xl">
Add
</GoAButton>
</>
)
}
```
```
<h3>Dynamic</h3>
<goa-tabs>
<goa-tab heading="1">Content 1</goa-tab>
<goa-tab heading="2">Content 2</goa-tab>
<goa-tab heading="3">Content 3</goa-tab>
<goa-tab *ngIf="isReport" heading="Report">Some Random Content</goa-tab>
</goa-tabs>
<goa-button (_click)="onClick()" mt="3xl">
Add
</goa-button>
```
```
export class TabsComponent {
isReport = false;
onClick() { …
```
=> fix: allow tabs to be dynamically added

libs/web-components/src/components/form-item/FormItem.spec.ts, libs/web-components/src/components/form-item/FormItem.svelte, libs/web-components/src/components/input/Input.spec.ts, libs/web-components/src/components/input/Input.svelte, libs/web-components/src/components/input/InputFormItemWrapper.test.svelte
The parent element sets the aria-label in the child (Input) element, but only when aria-label wasn't supplied in the input element i.e. it will not be overwritten.
Note: We decided not to set the 'for' attribute of the <label> tag in the parent i.e. FormItem... to be same as the id of the input. Because setting aria-label is enough. Tested locally with Chrome and Firefox using NVDA.
Some example code for angular playground. The `<div>` is added b/c `<goa-input>` may or may not always be the immediate child of `<goa-form-item>`
```
<h2>Case 1a - No arialabel provided (Expected: aria-lable gets set)</h2>
<goa-form-item label="DDD Id Provided" helptext="Maximum characters allowed are 10.">
<div>
<goa-input name="inputNameDesignAlberta1" maxlength="10" id="abcd-1234"></goa-input>
</div> …
```
=> fix(#1840): link form-item to Input for accessibility

libs/web-components/src/components/app-header/AppHeader.svelte
AppHeader and Microsite Header aren't aligned. 
This was merged  #1824 before but the change is somehow lost.
=> fix(#1438): update app header and microsite header padding

libs/web-components/src/components/dropdown/Dropdown.svelte
Change a selection on native dropdown doesn't trigger onChange event
```
onChangeNativeSelect(event: Event) {
// handle change
console.log((event as CustomEvent).detail.value);
}
```
```
<goa-form-item label="Basic dropdown">
<goa-dropdown native name="item" value="" (_change)="onChangeNativeSelect($event)">
<goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
<goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
<goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
</goa-dropdown>
```
=> fix: dispatch change event for native dropdown

libs/react-components/src/lib/radio-group/radio-group.spec.tsx, libs/react-components/src/lib/radio-group/radio.tsx, libs/web-components/src/components/radio-group/RadioGroup.html-data.json, libs/web-components/src/components/radio-group/RadioGroup.spec.ts, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/radio-group/RadioGroupWrapper.test.svelte, libs/web-components/src/components/radio-group/doc.md, libs/web-components/src/components/radio-item/RadioItem.html-data.json, libs/web-components/src/components/radio-item/RadioItem.spec.ts, libs/web-components/src/components/radio-item/RadioItem.svelte
Fixing bug #1859 
Example: 
1. Adding aria-label: 
```
<goa-radio-group name="color" arialabel="please select color" value="orange" (_change)="onChange($event)">
<goa-radio-item name="color" arialabel="you are choosing color red" value="red"></goa-radio-item>
<goa-radio-item name="color" arialabel="you are choosing color blue" value="blue">
<div slot="description">
<span class="customized-description-title">Content description</span>
<small> Another test?</small>
<p>
Help test
</p>
</div>
</goa-radio-item>
<goa-radio-item name="color" arialabel="you are choosing color orange" value="orange" description="Orange description">
</goa-radio-item>
</goa-radio-group>
```
2. Adding arialabelled-by:
```
<h2 id="radio-group-label">Basic with accessibility</h2>
<goa-radio-group name="color" …
```
=> fix(#1859): add arialabel to radio group and radio item

libs/web-components/src/components/form-step/FormStep.svelte, libs/web-components/src/components/form-step/form-step.spec.ts
Fired events twice on each form step change
Event is only fired once
Use steps in reported issue.
=> fix(#1395): eliminate duplicate events being fired on formstep change

libs/web-components/src/components/text-area/TextArea.spec.ts, libs/web-components/src/components/text-area/TextArea.svelte
Textarea doesnt show '0 characters remaining'
Textarea does show '0 characters remaining'
=> fix(#1737): textarea to show 0 characters remaining

libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte
https://jam.dev/c/9a8ae231-c3d9-4762-bff1-34ee4c03efe8
https://jam.dev/c/8db31b77-a73a-4fe8-9c69-c0ede712b240
=> fix(#1954): prevent dropdown firing _change event  when the value is reselected

libs/react-components/src/lib/radio-group/radio.tsx, libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/radio-item/RadioItem.spec.ts, libs/web-components/src/components/radio-item/RadioItem.svelte
This PR for https://github.com/GovAlta/ui-components/issues/1966 makes the following changes:
- Adds calculated margins to the radio item
- Removes bottom padding from the checkbox and radio item
- Uses a default medium bottom margin for the checkbox and radio item
=> feat(#1966): radio & checkbox bottom margin

libs/web-components/src/components/radio-group/RadioGroup.svelte
When reset is clicked, the radio item remained selected although the form values were reset.
Issue is fixed. See sample angular code below for testing.
An alternate solution (BUT **NOT A PREFERRED** SOLUTION) would be like below where we introduce a reset method in the svelte comp, and call it explicitly from angular.
```
Svelte
export function reset() {
setCurrentSelectedOption("");
}
Angular
<goa-radio-group #radioGroup goaValue formControlName="radioFormCtrl">
@ViewChild("radioGroup") radioGroup!: ElementRef; 
this.radioGroup.nativeElement.reset();
```
Copy paste the code below in your angular playground for testing. 
**html** 
```
<form [formGroup]="testForm">
<goa-form-item label="Input Test" mb="l">
<goa-input goaValue formControlName="inputFormCtrl" /> …
```
=> fix(#1974): fix radio reset angular issue

libs/web-components/src/components/popover/Popover.svelte
https://jam.dev/c/562fbffa-d1b1-4a66-8ff4-6c01f3562d08
https://jam.dev/c/6e547bb3-f60c-4ae9-9998-975c0799c836
Just make the window short, to make sure the option list of dropdown is on the top position.
=> fix/1802: filter dropdown has popover wrong position

libs/web-components/src/components/pagination/Pagination.svelte
Associated docs PR https://github.com/GovAlta/ui-components-docs/pull/194 
Copy paste the code from the comment below, in your Angular playground.
Scenario 1- Change the 'Show X of N' dropdown from 10 to 30
Bug: The 'Page 1 of N' dropdown still contains the range of 1 - 10. 
It should have been 1-4 only b/c 100 divided by 30 is 4 pages
Scenario 2- Now, change the 'Show X of N' dropdown from 30 to 20
Bug: The 'Page 1 of N' dropdown now shows 1 - 10 ...plus a new entry '5'...so a total of 11 items. 
It should have been 1-5 only.
The` {#key _pageCount}` rebinds the dropdown whenever the _pageCount is updated taking care of both the bugs mentioned above. With this change, the values in the dropdown are accurate.
Scneario 1 now contains 1,2,3,4 
Scenario 2 now contains 1,2,3,4,5
=> fix(#1680): fix paginaton issue when page count is changed

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
Text in File Upload Card will say "Maximum file size is `x`."
Text in File Upload Card will say "Maximum file size is 'x'"
Note the missing "." at the end.
Just use a File Upload Card
=> fix(#1716): Removed '.' from default file upload text

libs/react-components/src/lib/textarea/textarea.tsx
Doing a quick test with our React template demo app, I recognize our TextArea `onChange` and `onKeyPress` are not using our `GoABTextArea..` interface. 
Can use it now. 
```
<GoABFormItem label="Text area" error={errors.textarea} helpText="The text area can count the number of characters a user inputs.">
<GoABTextArea
width="100%" 
name="textarea" 
value={state.textarea} 
error={!!errors.textarea}
countBy="character"
maxCount={200}
onChange={(event: GoABTextAreaOnChangeDetail) =>
dispatch({ type: "textarea", payload: {"textarea": event.value} })
} 
/>
</GoABFormItem>
```
=> chore: update textarea onchange & onkeypress params

libs/web-components/src/components/form-stepper/FormStepper.svelte
- First-page content isn't displayed. 
- When we click/or first loaded page, the `_change` is triggered twice.
https://github.com/user-attachments/assets/017336d2-84e9-4d0b-b886-36aca1027db1
https://github.com/user-attachments/assets/d6f1b999-d6c8-493c-b32f-034a8ff2cd71
In Angular:
```
<h1>Form Stepper</h1>
<span>Current step {{step}}</span>
<goa-form-stepper ml="s" mr="s" [step]="step" (_change)="updateStep($event)">
<goa-form-step text="Personal details" [status]="status[0]"></goa-form-step>
<goa-form-step text="Employment history" [status]="status[1]"></goa-form-step>
<goa-form-step text="References" [status]="status[2]"></goa-form-step>
<goa-form-step text="Review" [status]="status[3]"></goa-form-step>
</goa-form-stepper>
<goa-pages [current]="step">
<div>Page 1 content with status: …
```
=> fix(#2033): step -1 doesn't show first page initially

libs/angular-components/src/lib/components/dropdown-item/dropdown-item.ts, libs/common/src/lib/common.ts, libs/react-components/src/lib/dropdown/dropdown-item.tsx
React has `mountType` but `angular-components` doesn't.
Angular component `goa-dropdown-item` has `mountType`
=> chore(#1980): add mountType to angular dropdown-item

libs/web-components/src/components/checkbox/Checkbox.svelte
This PR addresses #1147 with the following changes to the checkbox component:
When the checkbox is unselected...
- Hover:  Box uses an inner border
- Disabled: Label colour is `grey-500`
- Error: Box border colour is `interactive-error`
When the checkbox is selected...
- Hover:  Box uses an inner border
- Disabled:
- Label colour is `grey-500`
- Box colour is `interactive-disabled`
- Disabled & Hover: Box border doesn't change colour
- Error & Hover: Box border doesn't change colour
I couldn't find a fix for the below item in the issue:
> Focus ring needs to stay applied on focused option when user clicks the option
I don't think the issue is a CSS issue. Here's what I think is happening:
1. I focus on `input` using a keyboard so it has `focus-visible`.
2. I click `label` to toggle the …
=> fix(#1147): fix checkbox visual design issues

libs/web-components/global.html-data.json, libs/web-components/src/components/dropdown/Dropdown.html-data.json, libs/web-components/src/components/dropdown/DropdownItem.html-data.json
Using Angular in VSCode, the options for `mountType` were listed as "append", "prepend", and "replace"
The options for `mountType` should now be listed as "append", "prepend", and "reset"
=> fix(#2079): Changed mountType value

libs/react-components/src/lib/chip/chip.tsx, libs/web-components/src/components/chip/Chip.html-data.json, libs/web-components/src/components/chip/Chip.svelte
No way to change the theme of the `leadingicon` in the Chip component
`icontheme` property exists for Chip component, that modifies the theme of the icon included in `leadingicon`.
This can be tested with the following code:
```html
<goa-chip leadingicon="checkmark-circle" icontheme="filled" content="Chip text"></goa-chip>
<goa-chip leadingicon="checkmark-circle" content="Chip text"></goa-chip>
```
```javascript
<GoAChip leadingIcon="checkmark-circle" content="Chip text"></GoAChip>
<GoAChip
leadingIcon="checkmark-circle"
iconTheme="filled"
content="Chip text"
error
></GoAChip>
```
=> feat(#2080): Adding icontheme to Chip

libs/web-components/src/assets/css/components.css, libs/web-components/src/components/table/TableSortHeader.svelte
-Table headers are bottom aligned, 
-Text headers are left aligned
-Headers `<th>` having `class="goa-table-number-header"` like below are **right** aligned (example below)
```
<th class="goa-table-number-header">Reg Column</th>
<th class="goa-table-number-header">
<goa-table-sort-header name="age" direction="asc">Sortable Column</goa-table-sort-header>
</th>
```
=> fix(#1530): table bottom align headers

libs/react-components/src/lib/microsite-header/microsite-header.spec.tsx, libs/react-components/src/lib/microsite-header/microsite-header.tsx, libs/web-components/src/components/microsite-header/MicrositeHeader.spec.ts, libs/web-components/src/components/microsite-header/MicrositeHeader.svelte, libs/web-components/src/components/microsite-header/MicrositeHeaderWrapper.test.svelte
This PR allows slotted content in the "version" section of the microsite header. It's based off the previous work in the https://github.com/GovAlta/ui-components/pull/1853.
The `version` property on the microsite header only accepts a string.
The `version` property accepts slotted content...
...or a string.
The slotted `div` has the following layout to align with the [Figma design](https://www.figma.com/design/c7d7OviJ2Z04CrM66KLuiW/Enable-switching-between-library-versions-on-the-design-system-website?node-id=26-31830&t=hPQ9A3Y7Qpv7ucJJ-1):
- Is placed in a `flex` row
- Has a `space-m` gap
- Items are vertically aligned `center`
I also did a bit of tech debt. I replaced any stray `rem` values CSS with GOA space custom properties.
```html
<goa-microsite-header type="alpha" …
```
=> feat(#2053): allow slotted content in microsite header version

libs/web-components/src/components/modal/Modal.svelte
-No scrollbar/shadows for short content.
-For long content, shadows on the top/bottom or both depending on the scroll position.
-Buttons are right aligned together with padding considerations.
-Both usage work i.e. content surrounded by `<div slot="content">Lorem Ispsum.....</div>` and a div without the slot. Content not surrounded with any div also works
Angular Playground
modal-test.component.ts
```
import { Router } from "@angular/router";
@Component({
selector: "abgov-modal",
templateUrl: "./modal.component.html"
})
export class ModalComponent {
open = false;
onConfirm(event: Event) {
this.open = !this.open1;
}
onCancel(event: Event) {
this.open = false;
}
}
```
Example - Short content (no scroll, no shadow)
```
<goa-button …
```
=> fix(#2065): modal misc issues

libs/angular-components/src/lib/checked-directive.ts, libs/react-components/src/experimental/resizable-panel/ResizablePanel.tsx, libs/web-components/src/common/no-scroll.ts, libs/web-components/src/components/tooltip/Tooltip.svelte
Padding around the Tooltip component was defined as `--goa-space-xs` on top and bottom and `--goa-space-m` on the sides. Font typography was defined as `--goa-typography-body-s`
Padding around the Tooltip component is now defined as `--goa-space-m` on all sides. Font typography is `--goa-typography-body-m`
=> fix(#2088): Updated Tooltip font size and padding

libs/web-components/src/common/utils.ts
- [ x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
```
<div>Some Text</div>
<goa-text as="h2" mt="xl" mb="xl">
There should be padding above this text
</goa-text>
```
=> fix: prevent all the semicolons from being replaced with a space

libs/web-components/src/components/radio-item/RadioItem.svelte
This PR fixes some minor visual issues with the radio component to make it consistent with Figma. Changes include the following:
| Change | Before | After |
|--------|--------|--------|
| Button uses an inner border on hover | ![before - normal - hover](https://github.com/user-attachments/assets/21d992f6-fdf4-4d56-af13-feca1a8766d9) | ![after - normal - hover](https://github.com/user-attachments/assets/e67b8be5-eb6d-4cbb-8b9f-8522c4bfa86b) |
| Disabled label color is `grey-500` | ![image](https://github.com/user-attachments/assets/c6b71138-4700-47e0-a936-5be7c107ae6d) | ![image](https://github.com/user-attachments/assets/da85683e-194e-4543-a415-d6797a3c9fda) |
| Disabled button color is `grey-400`  | | | 
| Button border order width does not increase on focus | ![before - normal - …
=> fix(#1207): fix visual design issues on radio item

libs/react-components/src/lib/accordion/accordion.tsx, libs/react-components/src/lib/app-header/app-header.spec.tsx, libs/react-components/src/lib/app-header/app-header.tsx, libs/react-components/src/lib/callout/callout.tsx, libs/react-components/src/lib/side-menu-group/side-menu-group.spec.tsx, libs/react-components/src/lib/side-menu-group/side-menu-group.tsx, libs/react-components/src/lib/three-column-layout/three-column-layout.spec.tsx, libs/react-components/src/lib/two-column-layout/two-column-layout.spec.tsx, libs/web-components/src/assets/css/components.css, libs/web-components/src/components/accordion/Accordion.svelte, libs/web-components/src/components/app-header/AppHeader.svelte, libs/web-components/src/components/button/Button.svelte, libs/web-components/src/components/callout/Callout.svelte, libs/web-components/src/components/container/Container.svelte, libs/web-components/src/components/side-menu-group/SideMenuGroup.svelte, libs/web-components/src/components/table/Table.svelte, package-lock.json, package.json
If we want to have the look for those below 5 components:
* Accordion
* Button
* Callout
* Container
* Table
* SideMenuGroup
Like this figma design: https://www.figma.com/design/NRFUYjCwVoI9qMbFEG6s7J/Component-tokens?node-id=0-1&node-type=canvas&m=dev
It is impossible to override CSS right now, and if we override `--goa-text-default-color` for example, we will affect other components. 
This pull request is to add more specific design token variable names for those above 5 components, at the same time assigning values for those adding tokens, so it won't affect our components, but at the same time, allow other teams (specifically Privacy Portal Team) to override variable design token CSS (For example: https://github.com/vanessatran-ddi/latest-react-demo/blob/privacy-portal-components/src/o …
=> Feature/2162 & 2177 app header - privacy portal components + app header to trigger fly out menu

libs/web-components/src/components/accordion/Accordion.svelte, package-lock.json, package.json
Accordion padding is not correct:
The correct one should be like this: 
The padding is fixed, the padding when icon position is right, also being fixed. This PR is to upgrade the version of our package `@abgov/design-tokens`
=> fix(#2162): accordion padding for right and left icon position

libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/form-item/FormItem.spec.ts, libs/web-components/src/components/form-item/FormItem.svelte, libs/web-components/src/components/input/Input.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/text-area/TextArea.svelte
-The code adds appropriate aria-* attributes based on whether a field is required, has helper text and/or error text or both.
-When focused, the screen reader announces the helper text and/or error text
**Playground Test Code**
```
import { FormBuilder, FormControl, FormGroup, Validators } from "@angular/forms";
@Component({
selector: "abgov-radio",
templateUrl: "./radio.component.html",
styleUrls: ["./radio.component.css"],
})
export class RadioComponent {
form: FormGroup;
inputFormCtrl = new FormControl("");
radioFormCtrl = new FormControl("");
chkbox = new FormControl();
txtArea = new FormControl();
colorDropdown = new FormControl();
constructor(private fb: FormBuilder) {
this.form = new FormGroup({
inputFormCtrl: this.inputFormCtrl, …
```
=> fix(#2028): add accessibility features

libs/web-components/src/components/side-menu/SideMenu.svelte
```
::slotted(a), ::slotted(a:visited) {
color: var(--goa-color-text-default) !important;
}
```
So privacy portal team wants to override this color, they have no way to do. 
```
goa-side-menu .uiam--side-menu--sub-item.current {
font: var(--goa-typography-heading-s);
border-left: var(--goa-side-menu-child-border-width) solid var(--goa-color-interactive-disabled);
background: var(--goa-side-menu-child-color-bg-selected);
/* This color is rule that is not taking affect: */
color: var(--goa-color-interactive-default) !important;
}
```
We will fallback to the `goa-color-text-default` if the new token (customized color token) isn't defined (so it won't affect our DDI)
This is how they can "tweak" (I also inform Chase personally)
```
goa-side-menu .uiam--side-menu--sub-item.current {
font: …
```
=> fix(#2252): allow to override text color of sidemenu slotted::a

libs/web-components/src/components/side-menu-group/SideMenuGroup.svelte
Allow to have border-radius when we hover the menu, it is for privacy portal. 
For them, they can override the token that's already there. 
```
--goa-side-menu-group-border-radius: 15px;
```
For DDI component, there won't be affected:
=> fix(#2253): add border-radius for side-menu-group-heading

libs/react-components/src/lib/button/button.tsx, libs/web-components/src/components/button/Button.html-data.json, libs/web-components/src/components/button/Button.svelte
Request from Privacy portal team member: 
is it possible to adjust the width of the button (Continue as a guest) to full width as in figma?
Expected figma for the button "Continue as a guest" (Desktop)
Current:
Should be able to adjust the width:
And on mobile, the width is 100% so we can use a parent <div> to control its width. The first button set `width=100%`, the second button has `width` auto like now. 
React code snippet:
```
<GoAButton mt="m" type="secondary" leadingIcon="arrow-back" width="100%">
Back to personal information
</GoAButton>
<br/>
<GoAButton mt="m" type="secondary" leadingIcon="arrow-back">
Back to personal information
</GoAButton>
<br/>
```
=> feat(#1412): add width property for button

libs/angular-components/package.json
Angular 19 wasn't allowed
Angular 19 is allowed
Just need to test that you can install Angular 19 on a separate app outside of the playground
=> fix(#2279): Add support for Angular 19

libs/react-components/src/lib/textarea/textarea.spec.tsx, libs/react-components/src/lib/textarea/textarea.tsx, libs/web-components/src/components/text-area/TextArea.spec.ts
textarea react component does not expose readonly prop, like the textarea web component does.
textarea react component does expose readonly prop
Add textarea react component with readonly prop to react playground, then as a user try to change its input value. Expected result: Textarea can receive focus but won't accept keyboard input.
=> #1712 react readonly textarea

.github/workflows/lts-release-ci.yml, .releaserc.json, libs/angular-components/src/lib/value-directive.ts, libs/react-components/src/lib/input/input.tsx, libs/web-components/src/components/app-header/AppHeader.svelte
This is a spike ticket to understand how we can publish the major version on different branches/tags: 
- Running the command `npx semantic-release --dry-run` helps us understand the next version without actually publishing or tagging.
- semantic-release relies on the most recent Git tag and commit messages to calculate the next version according to Semantic Versioning:
* fix: Patch version bump (e.g., 1.0.1).
* feat: Minor version bump (e.g., 1.1.0).
* BREAKING CHANGE: Major version bump (e.g., 2.0.0).
As a result, I set up my testing repo (the reason why I cannot check on our `ui-components` is because I don't have enough permission): [example repo](https://github.com/vanessatran-ddi/test-npm-publish):
My testing repo has the below: 
1. main branch: Current tag is react-v5.3.0.
2. alpha …
=> fix(#2291): add workflow to release on different version and tag

libs/common/src/lib/common.ts
This PR is to release `@abgov/ui-components-common` on `alpha`, which failed due to the timeout in previous release.
=> fix(#2991): remove "sharp" from GoabChipTheme

libs/web-components/src/components/tabs/Tabs.svelte, libs/web-components/src/components/tabs/tabs.spec.ts
-If query string is present, it should be preserved. 
-Indicated tab should be honoured.
Angular playground code
```
<goa-tabs (_change)="handleTabChange($event)" initialtab="1">
<goa-tab>
<div slot="heading">Profile</div>
<p>
<b>Profile:</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</goa-tab>
<goa-tab>
<div slot="heading">
Review pending
<goa-badge type="important" content="1"></goa-badge>
</div>
<p>
<b>Review pending:</b> Lorem ipsum dolor sit amet, consectetur adipiscing
elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</goa-tab>
<goa-tab>
<div slot="heading">
Completed
<goa-badge type="midtone" content="1"></goa-badge>
</div>
<p>
<b>Completed:</b> Lorem ipsum dolor sit …
```
=> feat(#2109): tabs query string, loading 1st tab issues

.env, .gitignore, libs/web-components/vite.config.js
This change will allow for one to step through the code within the inspector, but still publish a minified file to npm.
1. Compile the web-components lib via `npx nx reset; npm run build` and note the file size (~760KB).
2. Create a `.env` file and add `VITE_DEV=true`
3. Recompile the project `npx nx reset; npm run build`. The new size of the build would be ~1.2MB
=> Vite config for prod only minification

libs/common/src/lib/validation.spec.ts, libs/common/src/lib/validators.ts
- all validators except for the requiredValidator, allow for blank values i.e. previous `optional` param is now true
Currently these validators are only being used in the public form so testing isn't required
=> fix: public form validator updates

libs/web-components/src/components/form-step/FormStep.svelte, libs/web-components/src/components/form-stepper/FormStepper.svelte
At version 1.20.0 (published 7 months ago), a developer can set icon “complete” for step 6 (final step) programmatically, by set Step 6 status Complete, and make [step]=7, something different from 1-> 6)
Using the below code: 
```
<goa-form-stepper
(_change)="updateCurrentStep($event)"
ml="s"
mr="s"
[step]="paymentBatchStatusStep"
class="non-clickable-stepper"
data-automation-id="payment-stepper"
>
<goa-form-step text="New" status="" [status]="paymentBatchStatusArray[0].status"></goa-form-step>
<goa-form-step text="Under Review" status="" [status]="paymentBatchStatusArray[1].status"></goa-form-step>
<goa-form-step
class="text-nowrap"
text="EO Recommendation"
[status]="paymentBatchStatusArray[2].status"
></goa-form-step>
<goa-form-step text="AO Approval" status="" …
```
=> fix(#2375): add "final" attribute to form-step

libs/angular-components/src/lib/components/filter-chip/filter-chip.spec.ts, libs/angular-components/src/lib/components/filter-chip/filter-chip.ts, libs/angular-components/src/lib/components/index.ts, libs/react-components/src/lib/filter-chip/filter-chip.spec.tsx, libs/react-components/src/lib/filter-chip/filter-chip.tsx
* `FilterChip` is being used as `GoAFilterChip` which isn't correct.
* Missing Angular component for `goab-filter-chip`
* 1835 document site is being affected, the code sandbox cannot generate correctly if new release is still use `GoA` prefix. 
Our document is correct as well as React/Angular code work:
=> fix(#2372): rename prefix GoA for FilterChip to goab

libs/react-components/src/lib/badge/badge.spec.tsx
Test was passing with a false-positive
Test is now finding element by `testId` attribute instead of the default, `data-testid` attribute.
Reason: While using react testing library with jsdom the shadow DOM is not visible the same as in a browser or when testing svelte components.
Run `libs\react-components\src\lib\badge\badge.spec.tsx`
=> fix(#2381): react getByTestId

.env.example, README.md
Local development environment needs a .env file with `VITE_DEV="true"` to prevent javascript minification of build output. A .env file used to be included in project until https://github.com/GovAlta/ui-components/commit/20587bc and now there is an extra manual step required to create the .env file.
Setup instructions updated to reference a new .env.example file that helps with creating the .env file. It's still a manual step but is more straightforward.
=> chore: update setup

libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/dropdown/DropdownWrapper.test.svelte
Filterable dropdown selected option broken when a) clicking an option to select, b) using arrows keys to highlight an option then pressing Enter to select, and c) when filterable dropdown input loses focus. Also, selected option in the DOM would not have "aria-selected=true".
Filterable dropdown selected option fixed when a) clicking an option to select, b) using arrows keys to highlight an option then pressing Enter to select, and c) when filterable dropdown input loses focus. Also, selected option in the DOM has "aria-selected=true".
Testing considerations: Tested in Chrome, Firefox
These Autofill Dropdown examples may be helpful for svelte, react and angular: https://github.com/user-attachments/files/19014103/2025-02-26-playground-examples.zip
=> fix(#2211): filterable dropdown selected option

_templates/web/src/pages/PopoverPage.svelte, libs/web-components/src/components/calendar/Calendar.svelte, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/input/Input.svelte, libs/web-components/src/components/popover/Popover.svelte, libs/web-components/src/components/popover/PopoverWrapper.test.svelte, libs/web-components/src/components/popover/popover.spec.ts
Dropdown uses Popover to show the list of options. Popovers had an invisible background behind them that user could click to close the popover. This prevented a user from clicking on anything behind the invisible background, like a hyperlink for example, until they clicked once to close the popover. This does not happen with a regular select. This problem affected Popover, Dropdown, AppHeader, AppHeaderMenu, and DatePicker.
Popover no longer has an invisible background and the component now handles a `focusout` event to decide if popover should be closed. Now it is possible to click outside of a popover to immediately interact with other elements, which is how a native select behaves:
<video src="https://github.com/user-attachments/assets/f19299f1-11da-452c-b1af-edf3655b9e28" …
=> fix(#1511) fix click outside popover

libs/web-components/src/components/radio-item/RadioItem.svelte
```html
<goab-form-item label="Select one option">
<goab-radio-group name="selectOne" value="1">
<goab-radio-item value="1" label="Option one" [description]="description">
<ng-template #description> Help text with a <a href="#">link</a>. </ng-template>
</goab-radio-item>
<goab-radio-item value="2" label="Option two" />
<goab-radio-item value="3" label="Option three" />
</goab-radio-group>
```
Make sure the `description` slot `font` property is styled using the correct design token
=> fix(#2474): Changing token used for radio description font

libs/web-components/src/components/app-header-menu/AppHeaderMenu.svelte, libs/web-components/src/components/app-header/AppHeader.svelte
App Header: Hovering over active AppHeaderMenu link makes font disappear #2434
Text colour was the same colour as the background on current page + hover, which made the text visually dissapear.
Text colour is now styled with correct token, and shows up as white with a dark blue (hover) background.
=> fix: text styling for hover on current page in app header menu

.github/workflows/alpha-release-ci.yml, .github/workflows/lts-release-ci.yml, .github/workflows/prod-release-ci.yml, .github/workflows/pull-request.yml
This should allow all the required `dist` sub-folders to exist and prevent the failed tests
=> chore: ensure all the `dist` builds exist on each PR

libs/web-components/src/components/date-picker/DatePicker.svelte
This better aligns with the common output format of MMMM d, yyyy
```
<goa-datepicker type="input" />
```
=> fix(#2551): reposition the order of inputs to M d y

libs/web-components/src/components/checkbox/Checkbox.spec.ts, libs/web-components/src/components/checkbox/Checkbox.svelte
When focusing or even using the mouse hovering the description slot, the screen reader doesn't recognize this `div` is a region that needs to be spoken out loud because it is under the shadow DOM. 
```
<goab-checkbox name="description" text="description slot" [description]="descriptionTemplate">
<ng-template #descriptionTemplate>
<p style="color: blue;">Example description inside a slot by Vanessa should be read aloud.</p>
</ng-template>
</goab-checkbox>
```
Developers can control what should be spoken out loud and what shouldn't. For example:
```
<goab-checkbox name="description" text="description slot" [description]="descriptionTemplate">
<ng-template #descriptionTemplate>
<div aria-hidden="true">
<p style="color: grey"> This text is hidden from screen readers </p>
</div>
<p …
```
=> feat(#2365): allow screen reader to announce description slot content

.github/CODEOWNERS
Nothing to be tested, just removing the CODEOWNERS file so that reviewers aren't auto assigned to every PR
=> chore: Removing the CODEOWNERS file

libs/angular-components/src/lib/components/input/input.spec.ts, libs/angular-components/src/lib/components/input/input.ts
`(onKeyPress)` wouldn't fire on the Input component for Angular
`(onKeyPress)` will fire on the Input component for Angular
```html
<goab-input (onKeyPress)="handleInputKeyDown()"> </goab-input>
```
```typescript
handleInputKeyDown() {
console.log("key pressed");
}
```
=> fix(#2586): Changed keypress event for Input for Angular

libs/web-components/src/components/tabs/Tabs.svelte
Related issue: https://github.com/GovAlta/ui-components/issues/2575
=> fix (#2575): Tab label not centered when the tab reaches the min width

apps/angular-tests/src/app/dropdown/dropdown.component.html, libs/angular-components/src/lib/components/date-picker/date-picker.ts, libs/angular-components/src/lib/components/dropdown/dropdown.spec.ts, libs/angular-components/src/lib/components/dropdown/dropdown.ts, libs/angular-components/src/lib/components/popover/popover.spec.ts, libs/angular-components/src/lib/components/popover/popover.ts, libs/common/src/lib/common.ts, libs/react-components/src/lib/date-picker/date-picker.spec.tsx, libs/react-components/src/lib/date-picker/date-picker.tsx, libs/react-components/src/lib/dropdown/dropdown.tsx, libs/react-components/src/lib/popover/popover.tsx, libs/web-components/src/components/app-header-menu/AppHeaderMenu.svelte, libs/web-components/src/components/app-header/AppHeader.svelte, libs/web-components/src/components/calendar/Calendar.svelte, libs/web-components/src/components/date-picker/DatePicker.html-data.json, libs/web-components/src/components/date-picker/DatePicker.svelte, libs/web-components/src/components/date-picker/date-picker.spec.ts, libs/web-components/src/components/date-picker/doc.md, libs/web-components/src/components/dropdown/Dropdown.html-data.json, libs/web-components/src/components/dropdown/Dropdown.spec.ts, libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/popover/Popover.html-data.json, libs/web-components/src/components/popover/Popover.svelte
Also see related ui-components-docs PR: https://github.com/GovAlta/ui-components-docs/pull/305
Popover had prop: "relative" that when enabled would add style, "position: relative;" to the popover container to help with positioning flow. Dropdown and DatePicker had "relative" prop that would be passed down to child popover component. Code was adjusted to always set style, "position: relative;" and to calculate the position of popover when displaying upwards.
Popover always has "position: relative" (related to #2003):
<video src="https://github.com/user-attachments/assets/bdc9255a-c743-4e1f-8180-c2f78d77539e" width="200"></video>
Popover positioning is still okay when scrolling within a modal (related to #2466):
<video src="https://github.com/user-attachments/assets/cafca2ec-8c13-45e8-a652-5 …
=> fix(#2003): popover remove relative prop

libs/web-components/src/components/spacer/Spacer.svelte
**Angular Playground Code**
```
<goab-block gap="none">
<div>FILL</div>
<goab-spacer hSpacing="fill"></goab-spacer>
<div>FILL</div>
<goab-spacer hSpacing="fill"></goab-spacer>
<div>FILL</div>
</goab-block>
```
```
import { GoabBadge, GoabBlock, GoabButton, GoabIcon, GoabInput, GoabSpacer, GoabTextArea } from "@abgov/angular-components";
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
@Component({
standalone: true,
selector: "abgov-spacing",
templateUrl: "./spacing.html",
imports: [
GoabInput,
GoabButton,
GoabIcon,
GoabSpacer,
GoabBlock,
GoabTextArea,
GoabBadge,
],
schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class SpacingComponent {
constructor() { }
}
```
=> fix(#2455): spacer hspacing fill doesnt work in Angular

libs/web-components/src/components/button/Button.svelte, libs/web-components/src/components/circular-progress/CircularProgress.svelte, libs/web-components/src/components/details/Details.svelte, libs/web-components/src/components/spinner/Spinner.spec.ts, libs/web-components/src/components/spinner/Spinner.svelte
This PR fixes some design token references on the following web components:
- Button
- Circular Progress
- Details
- Spinner
These are only CSS changes. There shouldn't be any impact on React, Angular, or unit tests.
The CSS custom parameters reference non-existent design tokens and are undefined.
The CSS custom parameters reference existing design token values.
=> fix(#2643): fix design token references

libs/angular-components/src/lib/components/modal/modal.ts, libs/web-components/src/components/modal/Modal.spec.ts, libs/web-components/src/components/modal/Modal.svelte, libs/web-components/src/components/modal/ModalWrapper.test.svelte
Scrollbar was not visible in react modal that has empty header
Modal header would not exist in DOM if not closeable and no heading or slotted heading provided. Modal used header for `aria-labelledby` and had no fallback `aria-label`.
Scrollbar is visible in react modal that has empty header
Modal header always exists in DOM but takes up no additional space when empty. When no heading or slotted heading provided there is a fallback `aria-label` for accessibility.
```tsx
const [modal3Open, setModal3Open] = useState(false);
const [alertDialog3Open, setAlertDialog3Open] = useState(false);
const [modal4Open, setModal4Open] = useState(false);
return (
<main>
<GoabButton onClick={() => setModal3Open(true)}>Open Header-less Dialog</GoabButton>
<GoabModal
role="dialog"
open={modal3Open}
>
<p>
When …
```
=> fix(#2415): modal empty header and heading accessibility

libs/web-components/src/components/input/Input.svelte
This is a fix for issue https://github.com/GovAlta/ui-components/issues/1219
This also fixes an additional bug where input type=date, datetime-local, and time, is 44px tall (should be 42px)
=> fix(1219): fixed height of input type date

libs/angular-components/src/lib/components/modal/modal.ts, libs/web-components/src/components/modal/Modal.spec.ts, libs/web-components/src/components/modal/Modal.svelte
In alpha version, angular templates used in modal did not work with modal the same as slots worked in LTS.
In alpha version, angular templates used in modal work with modal the same as slots worked in LTS.
```ts
isOpenModalUsingNgTemplate = false;
openModalUsingNgTemplate() {
this.isOpenModalUsingNgTemplate  = true;
}
closeModalUsingNgTemplate() {
this.isOpenModalUsingNgTemplate = false;
}
```
```html
<goab-button id="button2" (onClick)="openModalUsingNgTemplate()" ml="xs">Open Modal with actions and heading templates</goab-button>
<goab-modal id="modalUsingNgTemplate" [open]="isOpenModalUsingNgTemplate" [heading]="headingTemplate" [actions]="actionsTemplate">
<ng-template #headingTemplate><h1><i>Do you agree?</i></h1></ng-template>
<p>
Lorem ipsum dolor sit amet consectetur adipisicing …
```
=> fix(#2415): modal empty header and heading accessibility (angular)

libs/web-components/src/components/form-item/FormItem.svelte, libs/web-components/src/components/form/Fieldset.svelte, libs/web-components/src/components/form/FormSummary.svelte, libs/web-components/src/types/relay-types.ts
https://github.com/GovAlta/ui-components/issues/2690
- allows one to override the default sort order of fields within the form summary
- vertically aligns data within the form-summary table
Previously the birthdate (Datepicker) would always be displayed as the first item in the last section and the Address label would be vertically centred.
The below code will result in 
```html
<goa-fieldset>
<goa-form-item name="Your City" label="Foo City" helptext="Where you live">
<goa-input name="city"></goa-input>
<goa-form-item name="Address" label="Address">
<goa-textarea name="address"></goa-textarea>
<goa-form-item name="Postal Code" label="Postal Code">
<goa-input name="postal-code"></goa-input>
<goa-form-item name="Date of birth" label="Date …
```
=> 2690 - public form fixes

libs/web-components/src/components/input/Input.svelte
The ellipsis will be removed until a property that controls the ellipsis' visibility is added
=> fix: remove text-overflow ellipsis from input styles

libs/react-components/src/lib/input/input.tsx
https://github.com/user-attachments/assets/5f383afc-2624-4ceb-83b9-ee61c1270d1f
```
import { GoAInputDateTime } from "@abgov/react-components";
export default function Input() {
function noop() {
// noop
}
const [date, setDate] = useState<Date | string>("");
return (
<GoAInputDateTime
name={"ADSP test"}
value={date}
step={1}
onChange={(name, value: Date | string) => {
setDate(value);
console.log(value);
}}
/>
);
}
```
=> fix(#2526): date value mismatch seconds issue

libs/web-components/src/components/spacer/Spacer.svelte
- Vertical space provided by goa-spacer is not aligned with the spacing scale values.
- it looks like 3xs, 2xs, xs, s, and m are all too large, and stuck at the same height
- horizontal spacing appears to be correct
- Vertical space provided by goa-spacer should be correctly aligned with the spacing scale values. 
```
<div style={{ backgroundColor: "grey", padding: "16px", margin: "0" }}>
{" "}
none (below)
</div>
<GoabSpacer vSpacing="none"></GoabSpacer>
<div
style={{
backgroundColor: "#A7A7A7",
padding: "16px",
margin: "0",
}}
>
3xs
</div>
<GoabSpacer vSpacing="3xs"></GoabSpacer>
<div style={{ backgroundColor: "#A7A7A7", padding: "16px", margin: "0" }}>
2xs
</div>
<GoabSpacer vSpacing="2xs"></GoabSpacer>
<div style={{ backgroundColor: "#A7A7A7", padding: "16px", margin: "0" }}>
xs …
```
=> fix(#2770): goa-spacer vertical spacing issue

libs/angular-components/src/lib/components/checkbox/checkbox.spec.ts, libs/angular-components/src/lib/components/checkbox/checkbox.ts, libs/angular-components/src/lib/components/radio-item/radio-item.spec.ts, libs/angular-components/src/lib/components/radio-item/radio-item.ts, libs/react-components/src/lib/checkbox/checkbox.spec.tsx, libs/react-components/src/lib/checkbox/checkbox.tsx, libs/react-components/src/lib/radio-group/radio-group.spec.tsx, libs/react-components/src/lib/radio-group/radio.tsx, libs/web-components/src/common/utils.spec.ts, libs/web-components/src/common/utils.ts, libs/web-components/src/components/checkbox/Checkbox.spec.ts, libs/web-components/src/components/checkbox/Checkbox.svelte, libs/web-components/src/components/form-item/FormItem.svelte, libs/web-components/src/components/radio-group/RadioGroup.svelte, libs/web-components/src/components/radio-item/RadioItem.spec.ts, libs/web-components/src/components/radio-item/RadioItem.svelte
**Accordion:** 
and other components: 
You can use this code snippet to test:
HTML: https://gist.github.com/vanessatran-ddi/2901d56221c85c9580363896f7b130d1
TS: https://gist.github.com/vanessatran-ddi/0558044b4e010863e7f54d7cf9e45bd3
=> feat(#1216): add reveal slot to angular/react radio/checkbox

libs/angular-components/src/lib/components/input-number/input-number.ts, libs/angular-components/src/lib/components/input/input.ts, libs/common/src/lib/common.ts, libs/react-components/src/lib/input/input.tsx
You would have to use `GoaInputOnBlurDetail` for the `blur` event on the Input component
Now you can use `GoabInputOnBlurDetail` instead, `GoaInputOnBlurDetail` also still exists so existing use cases aren't wrecked.
=> fix(#2766): Added export for GoabInputOnBlurDetail

libs/web-components/src/components/hero-banner/HeroBanner.spec.ts, libs/web-components/src/components/hero-banner/HeroBanner.svelte
Hero Banner was changed to use the GoabText component.
This change has been undone and reverted back to using a standard `h1` tag instead
=> fix(#2765): Undid the addition of goab-text to Hero Banner

libs/web-components/src/components/text/Text.svelte
Margins were associated with the `tag` property that was used
Margins should instead be associated with the `size` property, the `tag` property should only be used to determine what element to output. Tag will determine size by using our default CSS provided for some of these tags (`h1`, `h2`, `p`, etc....), but will be overwritten if `size` is given.
Also, all margin bottoms have been changed. And a top margin calculation has been added.
`tag` span won't have any bottom or top margin no matter the `size` property, because it's an inline element, not a block element
```typescript
<GoabBlock gap="l" direction="column">
<GoabBlock gap="m" direction="column">
<h3>Margin Reference Test</h3>
<p>Compare margins across different sizes with the same tag:</p>
<div className="test-container"> …
```
=> fix(#2721): Updating Text component to give margins to size instead of tag

.github/workflows/alpha-release-ci.yml, .github/workflows/lts-release-ci.yml, .github/workflows/prod-release-ci.yml
There have been a few occasions that deloys have failed due to version tags already existing in Github. The reason for this **may** be due to the deployments happening in parallel.
=> chore: run nx publish in series

libs/web-components/src/components/dropdown/Dropdown.svelte, libs/web-components/src/components/popover/Popover.svelte
-Now accepts SPACE key
-Also fixed the focus issue (this was a pre-existing issue in prod, as soon as the space is entered, the focus goes all the way to the bottom)
**Angular Playground**
```
<div [formGroup]="fb">
<div style="margin-bottom:30px">
<goab-form-item label="Country">
<goab-dropdown
name="genderId"
width="40em"
placeholder="--Select Country--"
formControlName="countryDropdown"
[filterable]="true"
>
@for (country of countries; track country.code) {
<goab-dropdown-item [value]="country.code" [label]="country.name">
</goab-dropdown-item>
}
</goab-dropdown>
</div>
```
```
import {
GoabDropdown,
GoabDropdownItem,
GoabFormItem,
GoabButton,
} from "@abgov/angular-components";
import { FormControl, FormGroup, …
```
=> fix(#2852): cant use space in a filterable Dropdown

libs/react-components/specs/radio.browser.spec.tsx, libs/web-components/src/components/radio-group/RadioGroup.svelte
GoabRadioGroup couldn't have the `disabled` state changed programmatically after page load, it could only be set on page load.
GoabRadioGroup can now have its `disabled` state changed programmatically after page load.
```html
<goab-form-item label="GoabRadio" mb="xl">
<goab-radio-group [disabled]="radioDisabled">
<goab-radio-item value="option1" label="Option 1"></goab-radio-item>
<goab-radio-item value="option2" label="Option 2"></goab-radio-item>
</goab-radio-group>
<goab-button type="secondary" (click)="toggleRadio()" mb="2xl">
{{ radioDisabled ? "Enable Radio" : "Disable Radio" }}
</goab-button>
```
```typescript
radioDisabled = true;
toggleRadio(): void {
this.radioDisabled = !this.radioDisabled;
}
```
```typescript
const [radioDisabled, setRadioDisabled] = …
```
=> fix(#2768): Updated disable to update on change. Added test

.devcontainer.json, _templates/react/vite.config.ts, _templates/web/vite.config.mts
Previous commit had incorrect server settings for Vite config files,
which prevented the devcontainer from being accessible via the browser.# Before (the change)
=> chore: correct vite config to allow devcontainer to work

libs/web-components/src/components/form/Fieldset.svelte, libs/web-components/src/components/form/Form.svelte
Any entered invalid data would be immediately saved to the main form's state, which, through reloading the page after the invalid data was entered, allowed the user to be shown the form summary page with the data in an invalid state, thereby skipping the validation
Invalid state it no longer being saved, so if the user refreshes the browser after entering invalid data after clicking the "Change" link, the summary page will be shown, but with the data in the state that it was in prior to when the invalid data was entered.
Have a form with at least one "input" like item in it that has some validation attached to it. Enter data into the form field and then proceed to the summary page. Click the "Change" link on the page then enter some invalid data into the form field and click "Continue". …
=> remove unwanted saving of state on fieldset change handling

libs/react-components/src/lib/modal/modal.spec.tsx, libs/react-components/src/lib/modal/modal.tsx, libs/web-components/src/components/modal/Modal.svelte
This PR updates the Modal's React and Angular wrappers to better handle string headers. I used Drawer as a reference since it deals with a similar issue.
- The `isEmptySlot` function doesn't work correctly for React and Web.
- The React wrapper never added the `heading` property to the web component. So `_headingExists` was always false and the web component never added the proper padding.
- The `isEmptySlot` function works for Angular, React, and Web.
- The React wrapper adds the `heading` property if the heading is a string. The web component adds the correct padding.
=> fix(#2948): fix Modal spacing for heading and actions

libs/react-components/specs/dropdown.browser.spec.tsx, libs/react-components/src/lib/popover/popover.tsx, libs/web-components/src/components/focus-trap/FocusTrap.svelte, libs/web-components/src/components/menu-button/MenuButton.svelte, libs/web-components/src/components/popover/Popover.svelte
Just removing the exposed `tabIndex` prop from the React popover that was added in the multiaction button PR
=> chore: remove tabindex prop from React popover

libs/react-components/specs/menu-button.browser.spec.tsx, libs/react-components/src/lib/menu-button/menu-button.tsx
Updates the React library's MenuButton to use the same type as Angular does in the `onAction` event handler
=> fix: use the proper type for the React MenuButton event

libs/web-components/src/components/popover/Popover.svelte
The background of the popover button was visible when using a tertiary button as the popover target
```tsx
import { GoabBlock, GoabButton, GoabMenuAction, GoabMenuButton } from "@abgov/react-components";
import { GoabMenuButtonOnActionDetail } from "@abgov/ui-components-common";
export function TestContent() {
function handleAction(detail: GoabMenuButtonOnActionDetail): void {
console.log(detail.action)
}
return (
<GoabBlock direction="column">
<GoabMenuButton text={"Click me"} onAction={handleAction}>
<GoabMenuAction text={"ACtion 1"} action={"action-1"} />
<GoabMenuAction text={"ACtion 2"} action={"action-2"} />
<GoabMenuAction text={"ACtion 3"} action={"action-3"} />
</GoabMenuButton>
<GoabMenuButton type="secondary" text={"Click me"} onAction={handleAction}>
<GoabMenuAction …
```
=> fix: ensure popover's button is not visible

libs/web-components/src/components/accordion/Accordion.svelte
This PR updates the appearance of the Accordion component based on our Design System Evolution work.
When using the new design tokens, the accordion looks the same as the [experimental v2 Figma component](https://www.figma.com/design/Jpy1Ea5qglwnp1SgGnagY9/%E2%9D%96-Component-library-BETA?node-id=15932-570754&t=BaDG1i5FDhfwdFqU-1).
When using the current design tokens, the accordion looks the same as the [current Figma component](https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?m=auto&node-id=15932-570754&t=r7aLCk3jZ9F7W9Mx-1).
=> feat(#3057): update accordion styling to match v2 designs
