libs/web-components/demo/public/global.css
libs/web-components/demo/src/App.svelte
libs/web-components/src/Button.wc.svelte
libs/web-components/src/Container.wc.svelte
libs/web-components/src/Dropdown.wc.svelte
libs/web-components/src/Icon.wc.svelte
libs/web-components/src/IconButton.wc.svelte
libs/web-components/src/index.js

add Container component and component tweaks

---

.github/workflows/alpha-release-ci.yml
.github/workflows/beta-release-ci.yml
.github/workflows/prod-release-ci.yml

Fixes GovAlta/ui-components#260
add alpha workflow to deploy to dev
adjust beta workflow to only deploy to test and not to build storybook website because it's already built
add prod workflow to deploy to prod

Implement build pipeline for web components

---

libs/docs/.storybook/preview-head.html
libs/docs/src/components/Input.stories.mdx
libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx
libs/shared/storybook-common/src/index.ts
libs/shared/storybook-common/src/lib/Code/Code.css
libs/shared/storybook-common/src/lib/Code/Code.tsx
libs/web-components/rollup.config.js
libs/web-components/rollup.demo.config.js
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/input/Input.svelte
package.json

svelte and react input updates

---

libs/docs/src/components/common/Spinner.stories.mdx
libs/react-components/src/index.ts
libs/react-components/src/lib/spinner/spinner.spec.tsx
libs/react-components/src/lib/spinner/spinner.tsx
libs/web-components/src/components/button/Button.svelte
libs/web-components/src/components/spinner/Spinner.spec.ts
libs/web-components/src/components/spinner/Spinner.svelte

feat: add spinner tests and stories

---

libs/docs/src/angular-setup.stories.mdx
libs/docs/src/dev.stories.mdx
libs/docs/src/main.stories.mdx
libs/docs/src/react-setup.stories.mdx

chore: add npm versions on overview page

---

apps/demo/react/src/app/app.tsx
libs/docs/src/angular-setup.stories.mdx
libs/docs/src/components/common/FormItem.stories.mdx
libs/docs/src/react-setup.stories.mdx
libs/react-components/src/lib/form/form-item.spec.tsx
libs/react-components/src/lib/form/form-item.tsx
libs/web-components/demo/src/App.svelte
libs/web-components/src/components/form-item/FormItem.spec.ts
libs/web-components/src/components/form-item/FormItem.svelte
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/text-area/TextArea.svelte

Provides a consistent form field layout for labels, error messages and
helper text.

feat(#430): add form item component

---

apps/demo/angular-demo/src/app/app.component.html
apps/demo/angular-demo/src/app/app.component.ts
libs/docs/src/components/common/Radio.stories.mdx
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/radio-item/RadioItem.svelte

- storybook updates
- fix the missing focus state
- update disabled color to new value
- add example to angular demo
#267

radio button

---

libs/styles/src/lib/vars.css
libs/web-components/src/components/button/Button.svelte
libs/web-components/src/components/checkbox/Checkbox.svelte
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
libs/web-components/src/components/text-area/TextArea.svelte

Change from `--goa-color-interactive--highlight`
to `--goa-color-interactive--focus`

fix(#313): change css var name

---

libs/docs/src/components/common/Input.stories.mdx
libs/web-components/src/components/input/Input.svelte

updated to look like the following

fix input disabled styles

---

libs/web-components/src/components/input/Input.svelte

fix input vertical offset

---

libs/docs/src/components/common/Button.stories.mdx
libs/docs/src/components/common/Container.stories.mdx
libs/react-components/src/lib/button/button.spec.tsx
libs/react-components/src/lib/button/button.tsx
libs/react-components/src/lib/card/card.stories.mdx
libs/styles/src/lib/vars.css
libs/web-components/demo/src/App.svelte
libs/web-components/src/components/button/Button.spec.ts
libs/web-components/src/components/button/Button.svelte
libs/web-components/src/components/icon-button/IconButton.svelte

BREAKING CHANGE: The previous `small`, `medium` and `large` sizes have been replaced with `compact` and `normal`.

feat(#676): update Button for new design specs

---

libs/docs/src/components/common/Chip.stories.mdx
libs/react-components/src/index.ts
libs/react-components/src/lib/chip/chip.spec.tsx
libs/react-components/src/lib/chip/chip.tsx
libs/styles/src/lib/vars.css
libs/web-components/demo/src/App.svelte
libs/web-components/src/components/chip/Chip.spec.ts
libs/web-components/src/components/chip/Chip.svelte
libs/web-components/src/components/icon/Icon.svelte
libs/web-components/src/index.ts

- delete chip functionality is included

chip component

---

.prettierignore
libs/docs/src/components/common/FormItem.stories.mdx
libs/docs/src/components/common/Input.stories.mdx
libs/docs/src/components/common/TextArea.stories.mdx
libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx
libs/react-components/src/lib/textarea/textarea.spec.tsx
libs/react-components/src/lib/textarea/textarea.tsx
libs/web-components/demo/src/App.svelte
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/text-area/TextArea.spec.ts
libs/web-components/src/components/text-area/TextArea.svelte

With limit
With no limit
In a form item

feat(#682): add char count to input and textarea

---

libs/docs/src/components/common/Button.stories.mdx

https://goa-dio.atlassian.net/browse/DDIDS-584

update button storybook description and remove no longer needed examples

---

apps/angular-demo/angular.json
apps/angular-demo/package.json
apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.css
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.component.ts
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/button-component/button-component.component.html
apps/angular-demo/src/app/button-component/button-component.component.ts
apps/angular-demo/src/app/checkbox/checkbox.component.html
apps/angular-demo/src/app/checkbox/checkbox.component.ts
apps/angular-demo/src/app/dropdown/dropdown.component.html
apps/angular-demo/src/app/dropdown/dropdown.component.ts
apps/angular-demo/src/app/input-component/input-component.component.html
apps/angular-demo/src/app/input-component/input-component.component.ts
apps/angular-demo/src/app/modal/modal.component.html
apps/angular-demo/src/app/modal/modal.component.ts
apps/angular-demo/src/app/navigation-link/navigation-link.component.css
apps/angular-demo/src/app/navigation-link/navigation-link.component.html
apps/angular-demo/src/app/navigation-link/navigation-link.component.ts
apps/angular-demo/src/app/radio/radio.component.html
apps/angular-demo/src/app/radio/radio.component.ts
apps/angular-demo/src/app/text-area/text-area.component.html
apps/angular-demo/src/app/text-area/text-area.component.ts
apps/angular-demo/src/styles.scss

…ea code written to support cypress testing

DDI DS - 700 Cypress Test support : Button, Checkbox , Radio, Dropdown, Input ,TextArea and Modal code written to support cypress testing

---

libs/docs/src/components/common/CircularProgress.stories.mdx
libs/web-components/src/components/circular-progress/CircularProgress.svelte

DDI-765: add docs for the new default props

fix: allow for default props to circular progress component

---

.github/CODEOWNERS
libs/angular-components/README.md
libs/docs/src/angular-setup.stories.mdx
libs/docs/src/dev.stories.mdx
libs/docs/src/react-setup.stories.mdx
libs/react-components/README.md

Setup steps for setting up Angular and React libraries have been updated. And contribution steps have also been updated to be more accurate.

chore: Updated the readme's for all setup steps

---

libs/docs/src/components/common/TextArea.stories.mdx
libs/styles/src/lib/vars.css
libs/web-components/src/components/text-area/TextArea.svelte

fix(DDI-849): match textarea padding with UI specs

---

libs/react-components/src/lib/container/container.spec.tsx
libs/react-components/src/lib/container/container.tsx

fix(DDI-785): adding missing container padding attr in react

---

libs/react-components/package.json

This reverts commit ee508646231bf3340e89a3c33118bafde681c84e.

Revert "chore: update React peer deps to v18"

---

libs/docs/src/components/common/Button.stories.mdx

Added examples for variant, title and disabled props.

chore(DDI-975):adding missing examples of button component.

---

libs/docs/src/components/common/Badge.stories.mdx
libs/docs/src/components/common/Button.stories.mdx
libs/docs/src/components/common/Callout.stories.mdx
libs/docs/src/components/common/Checkbox.stories.mdx
libs/docs/src/components/common/Chip.stories.mdx
libs/docs/src/components/common/CircularProgress.stories.mdx
libs/docs/src/components/common/Container.stories.mdx
libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/FormItem.stories.mdx
libs/docs/src/components/common/HeroBanner.stories.mdx
libs/docs/src/components/common/Input.stories.mdx
libs/docs/src/components/common/Modal.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx
libs/docs/src/components/common/Skeleton.stories.mdx
libs/docs/src/components/common/TextArea.stories.mdx
libs/docs/src/components/goa/AppFooter.stories.mdx
libs/docs/src/components/goa/app-header.stories.mdx

Added missing property descriptions as per this [document](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2450129294/Component+Properties).

DDIDS-953-added-missing-property-descriptions

---

libs/docs/src/components/common/Container.stories.mdx

As discussed, added back the experimental types in the container component

fix(DDI-953): adding container types

---

libs/web-components/src/components/form-item/FormItem.svelte

Added margin-right to help text for resolving overlapping issue.

fix(DDI-1012): fixing overlap issue with help text and counter

---

libs/docs/src/components/common/Modal.stories.mdx
libs/web-components/src/components/modal/Modal.svelte

Added default value for transition prop to none in modal component

fix(DDI-1006): changing modal's default transition to none

---

libs/docs/src/components/common/Input.stories.mdx

Removed showcounter and maxcharcount from input component in storybook.

fix(DDI-1005): removed showcounter and maxcharcount from input component

---

libs/docs/src/components/common/Dropdown.stories.mdx
libs/web-components/src/components/dropdown/Dropdown.spec.ts
libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/dropdown/DropdownWrapper.test.svelte

Changed the dropdown's maxheight prop default value to 276px

chore(DDI-1003): changed default maxheight value in dropdown

---

libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx

Added callout message for name prop in storybook for dropdown and radio components

chore(DDI-1003): added callout message for name prop

---

libs/docs/src/components/common/Button.stories.mdx
libs/docs/src/components/common/Checkbox.stories.mdx
libs/docs/src/components/common/Chip.stories.mdx
libs/docs/src/components/common/Container.stories.mdx
libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/FormItem.stories.mdx
libs/docs/src/components/common/HeroBanner.stories.mdx
libs/docs/src/components/common/Input.stories.mdx
libs/docs/src/components/common/Modal.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx
libs/docs/src/components/common/Skeleton.stories.mdx
libs/docs/src/components/common/TextArea.stories.mdx
libs/docs/src/components/goa/AppFooter.stories.mdx
libs/docs/src/components/goa/app-header.stories.mdx
libs/docs/src/components/goa/microsite-header.stories.mdx

Adding different tabsets for angular and react where component props differ

chore(DDI-881): adding component prop tabset for angular and react

---

libs/docs/src/components/common/Chip.stories.mdx
libs/react-components/src/lib/chip/chip.tsx
libs/web-components/src/components/chip/Chip.svelte

Added a new property variant in the Chip component

feat(DDI-1002): Adding new property variant

---

libs/web-components/src/components/form-item/FormItem.svelte

Fixed label getting truncated if too long

fix(DDI-1040): label wrapping with parent container

---

libs/web-components/src/components/icon-button/IconButton.svelte

Changed icon button padding to 4px for all button sizes.

fix(DDI-994): Change padding to 4px

---

libs/web-components/src/components/icon-button/IconButton.svelte

Reverts GovAlta/ui-components#920

Revert "fix(DDI-994): Change padding to 4px"

---

apps/angular-demo/src/app/app-header/app-header.component.html
apps/angular-demo/src/app/badge/badge.component.html
apps/angular-demo/src/app/circular-progress/circular-progress.component.html
apps/angular-demo/src/app/container/container.component.html
apps/angular-demo/src/app/form-item/form-item.component.html
apps/angular-demo/src/app/hero-banner/hero-banner.component.html

Updating angular demo app with the latest changes.

chore(DDI-971): updating angular demo

---

apps/angular-demo/src/app/form-item/form-item.component.html
apps/react-demo/src/routes/formItem.tsx
libs/docs/src/components/common/FormItem.stories.mdx
libs/react-components/src/lib/form/form-item.spec.tsx
libs/react-components/src/lib/form/form-item.tsx
libs/web-components/src/components/form-item/FormItem.spec.ts
libs/web-components/src/components/form-item/FormItem.svelte

Renamed existing "optional" prop to "requirement". 
Added code to display optional and required labels.

chore(DDI-985): Added requirement prop

---

libs/web-components/src/components/form-item/FormItem.svelte

Added icon to the error message in form-item

feat(DDI-917): Added icon to the form-item error message

---

apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/button-group/button-group.component.html
apps/angular-demo/src/app/button-group/button-group.component.ts
apps/react-demo/src/app/app.tsx
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/buttonGroup.tsx
libs/docs/src/components/common/ButtonGroup.stories.mdx
libs/react-components/src/lib/button-group/button-group.tsx
libs/web-components/src/components/button-group/ButtonGroup.spec.ts
libs/web-components/src/components/button-group/ButtonGroup.svelte

Added storybook page for Button Group
Added new property "spacing" for button group component

feat(DDI-1059): Added storybook doc for button group

---

.storybook/manager.js
.vscode/launch.json
apps/angular-demo/src/app/modal/modal.component.html
apps/angular-demo/src/app/modal/modal.component.ts
apps/react-demo/src/routes/modal.tsx
babel-preset.js
libs/docs/src/components/common/Modal.stories.mdx
libs/react-components/.storybook/manager.js
libs/react-components/src/lib/modal/modal.tsx
libs/shared/storybook-common/assets/logo.htm
libs/shared/storybook-common/src/lib/callout/Callout.spec.tsx
libs/shared/storybook-common/src/lib/do-dont/DoDont.spec.tsx
libs/web-components/src/components/dropdown/Dropdown.spec.ts
libs/web-components/src/components/form-item/FormItem.svelte
libs/web-components/src/components/modal/Modal.spec.ts
libs/web-components/src/components/modal/Modal.svelte

Added callout variants for modal component.

Ddids 1031 callout modal

---

apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/notification-banner/notification-banner.component.html
apps/angular-demo/src/app/notification-banner/notification-banner.component.ts
apps/react-demo/src/routes/notificationBanner.tsx
libs/docs/src/components/common/NotificationBanner.stories.mdx
libs/react-components/src/lib/notification/notification.spec.tsx
libs/react-components/src/lib/notification/notification.tsx
libs/web-components/src/components/notification/Notification.svelte

Removed border radius from the banner.
Few files were formatted.

fix(DDIDS-1023): Removing border radius from notification banner

---

libs/web-components/src/components/modal/Modal.svelte

Adjusted border radius for callout variant
Adjusted padding for modals without callout
Added modal border and box-shadow properties

fix(DDIDS-1031): styling changes of callout modal

---

libs/web-components/src/components/modal/Modal.svelte

Removed the margin-bottom from last element in modal-content

fix(DDI-1031): Remove margin-bottom from last element in content area

---

apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/divider/divider.component.html
apps/angular-demo/src/app/divider/divider.component.ts
apps/react-demo/src/app/app.tsx
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/divider.tsx
libs/docs/src/components/common/Divider.stories.mdx
libs/react-components/src/lib/divider/divider.spec.tsx
libs/react-components/src/lib/divider/divider.tsx
libs/web-components/src/components/divider/Divider.svelte
libs/web-components/src/components/divider/divider.spec.ts

Added a storybook page for Divider component.
Added a new value "none" for "spacing" prop.

feat(DDI-1070): Added storybook doc for Divider component.

---

libs/react-components/src/lib/input/input.tsx

Fixed issue with datetime picker changing AM to PM and viceversa.

fix(DDI-1096): Fixed issue with AM changing to PM in datetime picker

---

libs/docs/src/components/common/Input.stories.mdx
libs/docs/src/dev.stories.mdx

Also updated the required flags on a few properties for Input

chore: Updated the commands to run when starting as a contributor

---

apps/angular-demo/src/app/checkbox/checkbox.component.html
apps/angular-demo/src/app/checkbox/checkbox.component.ts
apps/angular-demo/src/app/dropdown/dropdown.component.html
apps/angular-demo/src/app/dropdown/dropdown.component.ts
apps/angular-demo/src/app/input-component/input-component.component.html
apps/angular-demo/src/app/input-component/input-component.component.ts
apps/angular-demo/src/app/radio/radio.component.html
apps/angular-demo/src/app/radio/radio.component.ts
apps/angular-demo/src/app/text-area/text-area.component.html
apps/angular-demo/src/app/text-area/text-area.component.ts
libs/docs/src/components/common/Checkbox.stories.mdx
libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/Input.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx
libs/docs/src/components/common/TextArea.stories.mdx

Added reactive binding examples for text area, dropdowns, radio buttons, checkbox and input components.

feat(DDI-1095): Added reactive binding examples

---

apps/react-demo/src/routes/checkbox.tsx
apps/react-demo/src/routes/dropdown.tsx
apps/react-demo/src/routes/input.tsx
apps/react-demo/src/routes/radio.tsx
apps/react-demo/src/routes/textarea.tsx
libs/docs/src/components/common/Checkbox.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx
libs/react-components/src/lib/checkbox/checkbox.tsx
libs/react-components/src/lib/dropdown/dropdown.tsx
libs/react-components/src/lib/input/input.tsx
libs/react-components/src/lib/radio-group/radio-group.tsx
libs/react-components/src/lib/textarea/textarea.tsx
libs/web-components/src/components/checkbox/Checkbox.svelte
libs/web-components/src/components/radio-group/RadioGroup.svelte

Added examples of ariaLabel property used for all inputs in React demo
Added ariaLabel property for checkbox and radio components
Updated documentation for checkbox and radio components to include new property
Updated react components for all inputs to include ariaLabel property

fix(DDI-1108): Update aria-label property for all inputs

---

apps/angular-demo/src/app/hero-banner/hero-banner.component.html
apps/react-demo/src/routes/heroBanner.tsx
libs/docs/src/components/common/HeroBanner.stories.mdx
libs/react-components/src/lib/hero-banner/hero-banner.spec.tsx
libs/react-components/src/lib/hero-banner/hero-banner.tsx
libs/web-components/src/components/hero-banner/HeroBanner.spec.ts
libs/web-components/src/components/hero-banner/HeroBanner.svelte

Added a new property minHeight
Added unit tests to verify the minHeight property
Added examples in Angular and React demo

Ddi 1119 minheight property

---

apps/angular-demo/src/app/input-component/input-component.component.html
apps/react-demo/src/routes/input.tsx
libs/docs/src/components/common/Input.stories.mdx
libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/input/Input.test.svelte

Added two new properties leadingContent and trailingContent in the input component.
Added warning message to show when prefix/suffix are used.
Updated tests accordingly.

feat(DDI-1101): Added slots for leading and trailing contents

---

libs/docs/src/components/common/Modal.stories.mdx
libs/docs/src/components/common/Skeleton.stories.mdx
libs/web-components/src/components/badge/Badge.spec.ts
libs/web-components/src/components/badge/Badge.svelte
libs/web-components/src/components/callout/Callout.svelte
libs/web-components/src/components/circular-progress/CircularProgress.svelte
libs/web-components/src/components/container/Container.svelte
libs/web-components/src/components/form-item/FormItem.svelte
libs/web-components/src/components/icon-button/IconButton.svelte
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
libs/web-components/src/components/modal/Modal.svelte
libs/web-components/src/components/notification/Notification.svelte
libs/web-components/src/components/radio-group/RadioGroup.svelte
libs/web-components/src/components/skeleton/Skeleton.svelte

Added typeValidation to all properties having multiple values

feat(DDI-1084): Adding typeValidation to components

---

libs/styles/src/lib/fonts.css

Added new font-face roboto-mono

feat(DDI-919): Adding new font-face roboto-mono

---

libs/docs/src/components/common/Checkbox.stories.mdx

Added example in checkbox component to bold the checkbox label

feat(DDI-1151): Added example for formatting options

---

libs/angular-components/package.json

Added peerDependencies for @angular/core in angular components

chore(DDI-1157): added peerDependencies for angular/core

---

libs/web-components/src/components/input/Input.svelte

Updated the font for all the input types to be same.

feat(DDI-1140): Updated same font for all input types

---

libs/angular-components/package.json

Changed the version from 12.x to 12.0.0

fix(DDI-1157): version change

---

libs/docs/src/components/common/Skeleton.stories.mdx
libs/web-components/src/components/skeleton/Skeleton.svelte

Added example for linecount prop

feat(DDI-998): Added example for linecount prop

---

libs/docs/src/components/common/Dropdown.stories.mdx

Added examples of leadingicon, maxheight, placeholder, width, and disabled properties for the dropdown component

feat(DDI-999): Added examples for dropdown props

---

libs/docs/src/BrowserSupport.stories.mdx

Added storybook page for supported browsers and devices.

feat(DDI-331): Added doc for supported browsers

---

libs/docs/src/components/common/TwoColumnLayout.stories.mdx

Added the descriptions for examples in two column layout doc

feat(DDI-1148): Update two column layout doc

---

apps/angular-demo/src/app/accordion/accordion.component.html
apps/angular-demo/src/app/accordion/accordion.component.ts
apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.module.ts
apps/react-demo/src/app/app.tsx
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/accordion.tsx
libs/docs/src/components/common/Accordion.stories.mdx
libs/react-components/src/index.ts
libs/react-components/src/lib/accordion/accordion.spec.tsx
libs/react-components/src/lib/accordion/accordion.tsx
libs/web-components/src/components/accordion/Accordion.spec.ts
libs/web-components/src/components/accordion/Accordion.svelte
libs/web-components/src/index.ts

https://goa-dio.atlassian.net/browse/DDIDS-1133

[DDIDS-1133] Accordion Component

---

.github/workflows/alpha-release-ci.yml
.github/workflows/prod-release-ci.yml
README.md
apps/angular-demo/src/app/accordion/accordion.component.html
apps/angular-demo/src/app/accordion/accordion.component.ts
libs/angular-components/README.md
libs/docs/src/BrowserSupport.stories.mdx
libs/docs/src/components/common/Accordion.stories.mdx
libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/TwoColumnLayout.stories.mdx
libs/docs/src/dev.stories.mdx
libs/react-components/README.md
libs/react-components/src/lib/accordion/accordion.spec.tsx
libs/react-components/src/lib/accordion/accordion.tsx
libs/web-components/README.md

https://goa-dio.atlassian.net/browse/DDIDS-1180
https://goa-dio.atlassian.net/browse/DDIDS-1181
https://goa-dio.atlassian.net/browse/DDIDS-1202
* Update Readme files
* Update release ci files to manually include the web-components readme file as the current version of `nx` doesn't seem to support including static files into the build
* My git hooks are working again so some formatting changes 😅

chore(DDIDS:1180, DDIDS-1181, DDIDS-1202) Update docs for npmjs and github

---

apps/angular-demo/src/app/notification-banner/notification-banner.component.html
apps/angular-demo/src/app/notification-banner/notification-banner.component.ts
apps/react-demo/src/routes/notificationBanner.tsx
libs/docs/src/components/common/NotificationBanner.stories.mdx
libs/react-components/src/lib/notification/notification.spec.tsx
libs/react-components/src/lib/notification/notification.tsx
libs/web-components/src/components/notification/Notification.spec.ts
libs/web-components/src/components/notification/Notification.svelte

Added onDismiss property in notification banner component

feat(DDI-1176): Added ondimiss prop in the notification banner component

---

libs/docs/src/components/common/Dropdown.stories.mdx
libs/docs/src/components/common/Radio.stories.mdx

Removed the empty note from dropdown and radio documentation

fix(DDI-1223): removed the random note from dropdown and radio doc

---

apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/styles/styles.component.html
apps/angular-demo/src/app/styles/styles.component.ts
apps/react-demo/src/app/app.tsx
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/styles.tsx
libs/docs/src/components/common/Lists.stories.mdx
libs/docs/src/components/common/Table.stories.mdx
libs/web-components/src/assets/css/components.css

Also updated Table documentation to include an area specifically for number columns, instead of sharing a section with sortable.

feat(DDI-1236): Creating styles for list elements and documenting

---

.storybook/abTheme.js

Updated GoA logo link to https://ui-components.alberta.ca

fix(DDI-1194): update storybook link

---

apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.component.html
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/icon/icon.component.html
apps/angular-demo/src/app/icon/icon.component.ts
apps/react-demo/src/app/app.tsx
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/icon.tsx
libs/docs/src/components/common/Icon.stories.mdx

Added storybook page for icon component
Design: https://www.figma.com/file/AedpWLVFBdEwWDRBUEgwUJ/Icon-layout?t=Ti7SFT43hq5Z99JX-0

feat(DDI-1239): Added docs for icon component

---

libs/web-components/src/assets/css/fonts.css
libs/web-components/src/assets/css/reset.css

Removed an import statement that ublock had an issue with, as the css is empty
Added fallback fonts

fix(DDI-1166): removed empty import and added fallback fonts

---

libs/docs/src/components/common/Table.stories.mdx

Updated handleSort code to be same as angular demo app

fix(DDI-1267): Updated handleSort code

---

libs/docs/src/components/common/Input.stories.mdx
libs/web-components/src/components/input/Input.html-data.json

Updated input props (min, max and step) description

fix(DDI-1253): Updated input props desc

---

libs/docs/src/components/common/Button.stories.mdx

Remove button placement link from button component doc

fix(DDI-1253): remove button placement link

---

libs/angular-components/CHANGELOG.md
libs/react-components/CHANGELOG.md
libs/web-components/CHANGELOG.md

Tagged this with a fix to ensure a build is done on each library to update its version and force the Changelogs to be present.

fix: Updating CHANGELOG(s)

---

libs/web-components/src/components/badge/Badge.svelte

Removed casing on badge content

Ddids 1272 badge content casing

---

apps/angular-demo/src/app/icon-button/icon-button.component.html
apps/react-demo/src/routes/iconButton.tsx
libs/docs/src/components/common/IconButton.stories.mdx
libs/react-components/src/lib/icon-button/icon-button.spec.tsx
libs/react-components/src/lib/icon-button/icon-button.tsx
libs/web-components/src/components/icon-button/IconButton.html-data.json
libs/web-components/src/components/icon-button/IconButton.spec.ts
libs/web-components/src/components/icon-button/IconButton.svelte

Added a new variant "destructive" in the icon button component.

feat(DDI-1235): add new icon button variant

---

apps/angular-demo/src/app/dropdown/dropdown.component.html
apps/react-demo/src/routes/dropdown.tsx
libs/web-components/src/components/dropdown/Dropdown.spec.ts
libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/dropdown/DropdownWrapper.test.svelte

The dropdown selected value is not being changed programmatically. 
Before with the below code: 
```
<h2>Reactive Binding
<GoAButton onClick={() => setSelectedColor("red")} type="tertiary">
Change to red
</GoAButton>
</h2>
<div>Selected Color: {selectedColor}</div>
<br/>
<GoADropdown name="colors" placeholder="Select a color" onChange={(e) => setSelectedColor(e)} value={selectedColor}>
<GoADropdownItem key="red" value="red" label="Red" />
<GoADropdownItem key="green" value="green" label="Green" />
<GoADropdownItem key="value" value="blue" label="Blue" />
</GoADropdown>
```
**The value of the dropdown is not changed when we click the button.** 
- [DDIDS-1277](https://goa-dio.atlassian.net/browse/DDIDS-1277)
Step 1: Pull this PR and build web components ```npm run build:web-components``` …

fix(DDI-1277) selected value not being changed programmatically

---

libs/web-components/src/components/dropdown/Dropdown.svelte

- Adjusted dropdown menu to show "up" when dropdown is at bottom of the page.
- Disabled scroll when dropdown menu is open

feat(DDI-781): Adjust dropdown menu position

---

apps/angular-demo/src/app/app.component.html
libs/web-components/src/common/utils.ts
libs/web-components/src/components/badge/Badge.svelte
libs/web-components/src/components/callout/Callout.svelte
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
libs/web-components/src/components/notification/Notification.svelte
libs/web-components/src/components/skeleton/Skeleton.svelte

Console error is seen when variables are used with the following properties
- Badge - type prop
- Callout - type prop
- Microsite Header - type prop
- Notification - type prop
- Skeleton - type prop

fix(DDI-1274): Added timeout before validating props

---

libs/web-components/src/components/icon/Icon.svelte

fix(DDI-1283): remove icon hover state

---

apps/angular-demo/src/app/app-footer/app-footer.component.html
apps/angular-demo/src/app/app-routing.module.ts
apps/angular-demo/src/app/app.module.ts
apps/angular-demo/src/app/three-column-layout/three-column-layout.component.html
apps/angular-demo/src/app/three-column-layout/three-column-layout.component.ts
apps/react-demo/src/main.tsx
apps/react-demo/src/routes/appFooter.tsx
apps/react-demo/src/routes/threeColumnLayout.tsx
libs/docs/src/components/common/ThreeColumnLayout.stories.mdx
libs/react-components/src/lib/three-column-layout/three-column-layout.spec.tsx
libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte

Add padding between heading and dividing line.
[DDI-1293](https://goa-dio.atlassian.net/browse/DDIDS-1293)

fix(DDI-1293): add padding bottom to AppFooter's heading

---

apps/angular-demo/src/app/form-stepper/form-stepper.component.html
apps/react-demo/src/routes/callout.tsx
libs/docs/src/components/common/Callout.stories.mdx
libs/docs/src/components/common/FormStepper.stories.mdx
libs/react-components/CHANGELOG.md
libs/web-components/src/components/icon/Icon.svelte

No onHover or onFocus treatments on Icons (onFocus with tab)
Maintain current treatments on Icon Button
[DDI-1283](https://goa-dio.atlassian.net/browse/DDIDS-1283)
https://user-images.githubusercontent.com/120135417/234907878-5d0c2c46-8b2c-4a4a-9fa1-1a6c085657c8.mov

fix(DDI-1283): remove hover icon hover state

---

libs/docs/src/components/common/Modal.stories.mdx

Removed closable prop from React lang properties table

fix(DDI-1318): remove closable prop from react

---

libs/web-components/src/components/modal/Modal.svelte

Updated padding and margins of modal component for mobile view.

chore(DDI-1306): updated padding for modal mobile view

---

apps/react-demo/src/routes/table.tsx
libs/docs/src/components/common/Table.stories.mdx
libs/react-components/src/index.ts
libs/react-components/src/lib/table/table-sort-header.spec.tsx
libs/react-components/src/lib/table/table-sort-header.tsx
libs/react-components/src/lib/table/table.spec.tsx

Added react wrapper for goa-table-sort-header, and updated storybook and react demo examples

chore(DDI-1319): Added react wrapper for table-sort-header

---

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte

Updated border on Hover to a dashed line
Changed padding to 32px (--goa-spacing-xl) and top padding to 28px on vertical version
Updated spacing between icon and text (Drag and Drop files…) to --goa-spacing-s (12px)

fix(DDI-1321): CSS Changes

---

apps/angular-demo/src/app/app.component.ts
apps/angular-demo/src/app/menus.ts
libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
libs/web-components/src/components/focus-trap/FocusTrap.svelte
libs/web-components/src/components/sidebar/Sidebar.html-data.json
libs/web-components/src/components/sidebar/Sidebar.svelte
libs/web-components/src/components/sidebar/SidebarItem.html-data.json
libs/web-components/src/components/sidebar/SidebarItem.svelte
libs/web-components/src/components/sidebar/SidebarWrapper.test.svelte
libs/web-components/src/components/sidebar/doc.md
libs/web-components/src/components/sidebar/sidebar.spec.ts
libs/web-components/src/index.ts

Side menu (collaboration with CS platform team) - First version - Angular supported.
- Sidebar and SidebarItem svelte components added
- Handle multi-level items. However, for now, the design (CSS styles) is supported for 2-level menu items. 
- Unit tests added 
- Angular demo app added 
This is our Angular demo app:
This is the demo site:
https://vanessatran-ddi.github.io/angular-ui-component-sample/home
This is the accessibility feature that works: 
https://github.com/GovAlta/ui-components/assets/120135417/897b7af6-53d7-45ee-86f0-0a6a7f3a15ae

DDI-1352: Left side menu - 1st version - Angular

---

libs/docs/src/components/common/FileUpload.stories.mdx

Updated angular code under Basic example of File Upload component

fix(DDI-1327): Updated angular code sample

---

apps/angular-demo/src/app/badge/badge.component.html
libs/docs/src/components/common/Badge.stories.mdx
libs/react-components/src/lib/badge/badge.spec.tsx
libs/react-components/src/lib/badge/badge.tsx
libs/web-components/src/components/badge/Badge.html-data.json
libs/web-components/src/components/badge/Badge.spec.ts
libs/web-components/src/components/badge/Badge.svelte
libs/web-components/src/components/icon/Icon.html-data.json
libs/web-components/src/components/icon/Icon.spec.ts
libs/web-components/src/components/icon/Icon.svelte
libs/web-components/src/components/icon/doc.md

Update badge component so that the screen reader can parse them. 
Talk to Mark and Dustin about it. This is the  [demo site](https://vanessatran-ddi.github.io/angular-ui-component-sample/badge) that we discussed and agreed on, especially about how the screen reader should read/announce it. 
https://github.com/GovAlta/ui-components/assets/120135417/de52a0c8-d240-4f5e-824e-1038631546ac

feat(DDI-1309): Update the accessibility of badge component.

---

apps/angular-demo/src/app/app.component.html
apps/react-demo/src/app/app.tsx
libs/react-components/src/lib/tooltip/tooltip.tsx

Just a PR to merge BUGFIX into alpha

fix(#1306): Tooltip react component type fix

---

apps/angular-demo/src/app/hero-banner/hero-banner.component.html
libs/docs/src/components/common/HeroBanner.stories.mdx
libs/react-components/src/lib/hero-banner/hero-banner.spec.tsx
libs/react-components/src/lib/hero-banner/hero-banner.tsx
libs/web-components/src/components/hero-banner/HeroBanner.html-data.json
libs/web-components/src/components/hero-banner/HeroBanner.svelte
libs/web-components/src/components/hero-banner/doc.md

Follow PR #1337, and address PR comments.

feat(#1295) Hero banner upgrades

---

libs/docs/src/components/common/TextArea.stories.mdx
libs/react-components/src/lib/textarea/textarea.spec.tsx
libs/react-components/src/lib/textarea/textarea.tsx
libs/web-components/src/common/utils.ts
libs/web-components/src/components/form-item/FormItem.svelte
libs/web-components/src/components/text-area/TextArea.spec.ts
libs/web-components/src/components/text-area/TextArea.svelte

To test
```
<goa-form-item label="No counters">
<goa-textarea width="100%" />
<goa-form-item label="count by char">
<goa-textarea width="100%" countby="character" showcount on:_change={(e) => console.log(e.detail.value)} />
<goa-form-item label="count by char with limit">
<goa-textarea countby="character" maxcount={20} width="100%" />
<goa-form-item label="count by word">
<goa-textarea countby="word" width="100%" />
<goa-form-item label="count by word with limit">
<goa-textarea countby="word" maxcount={5} width="100%" />
<goa-form-item label="Disabled">
<goa-textarea countby="character" maxcount={20} width="100%" disabled />
```

Textarea counter

---

libs/web-components/playground/src/pg-pagination.svelte
libs/web-components/src/components/dropdown/Dropdown.svelte

Fixing issue #1458 , the issue happens only in React.

fix(#1458): page number not working for pagination - react

---

libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx

I have a svelte4 upgrade PR at https://github.com/chrisolsen/ui-components/pull/1 for @chrisolsen  to review there too.

fix(#1532): GoAInputNumber - decimal number should be passed back

---

libs/angular-components/src/lib/value-directive.ts

BREAKING CHANGE: this commit will be later reverted to push a new *minor* release to sync back up with npm

fix!: change to trigger a major release

---

libs/angular-components/src/lib/value-directive.ts

BREAKING CHANGE: this commit will be later reverted to push a new *minor* release to sync back up with npm

Production Release: Trigger breaking change in Angular

---

libs/web-components/src/components/footer-meta-section/FooterMetaSection.svelte

Follow-up closed PR #1552 
The request was long time ago by Mark, described by this issue #1654

chore(#1654): footer meta section - change gap to l

---

libs/web-components/src/components/hero-banner/HeroBanner.svelte
package.json

```
import "abgov/react-components";
export function HeroBannerPage() {
return (
<>
<GoAHeroBanner heading="Heading">
<GoAHeroBannerActions>
<GoAButton type="start" onClick={() => { /* nothing */ }}>
Call to action
</GoAButton>
</GoAHeroBannerActions>
</GoAHeroBanner>
</>
)
}
export default HeroBannerPage;
```

hero banner centering

---

libs/react-components/src/lib/app-header/app-header.tsx
libs/web-components/src/components/app-header/AppHeader.spec.ts
libs/web-components/src/components/app-header/AppHeader.svelte
libs/web-components/src/components/app-header/AppHeaderWrapper.test.svelte

The bug is described at https://github.com/GovAlta/ui-components/issues/1377
Solution implemented: I add a new flag `fullmenuwidth` like Chris commented. https://github.com/GovAlta/ui-components/issues/1377#issuecomment-1930274360
As you can see in the video below, the screen is > 1024px (our breakpoint), and thanks to the added flag, I can make the menu to collapse like I want, depends on the context (menu collapse even when the screen is < 1700 based on my testing logic)
Screenshot/video: 
https://github.com/GovAlta/ui-components/assets/120135417/a090c1ae-b3d4-4f81-a594-7e1c51969fce
The code below for testing:
Angular:
```
<goa-two-column-layout maxcontentwidth="1400px" navcolumnwidth="30ch">
<section slot="header">
<goa-microsite-header
type="alpha"
level="alpha"
version="UAT" …
```

fix(#1377): add fullmenuwidth to goa-app-header - need code review

---

_templates/react/vite.config.ts
libs/react-components/package.json
libs/react-components/src/experimental/index.ts
libs/react-components/src/experimental/resizable-panel/ResizablePanel.module.css
libs/react-components/src/experimental/resizable-panel/ResizablePanel.tsx
libs/react-components/src/index.ts
libs/react-components/vite.config.ts
libs/web-components/src/common/styling.ts
libs/web-components/src/components/accordion/Accordion.svelte
libs/web-components/src/components/block/Block.svelte
libs/web-components/src/components/button/Button.svelte
libs/web-components/src/components/card/Card.svelte
libs/web-components/src/components/container/Container.svelte
libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/file-upload-card/FileUploadCard.svelte
libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
libs/web-components/src/components/footer/Footer.svelte
libs/web-components/src/components/form-step/FormStep.svelte
libs/web-components/src/components/form-stepper/FormStepper.svelte
libs/web-components/src/components/grid/Grid.svelte
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
libs/web-components/src/components/notification/Notification.svelte
libs/web-components/src/components/pagination/Pagination.svelte
libs/web-components/src/components/skeleton/Skeleton.svelte
libs/web-components/src/components/spacer/Spacer.svelte
libs/web-components/src/components/tabs/Tabs.svelte
libs/web-components/src/components/text-area/TextArea.svelte
libs/web-components/vite.config.js

The following components have `@container` queries
- accordion
- container
- fileupload input and card
- footer
- grid
- microsite header
- notification
- pagination
- skeleton (card only)
- tabs
- textarea
Some [React code](https://gist.github.com/chrisolsen/5c80cc12c7401ee0e3ebb6df1cc7ccec) to help with the testing

container queries

---

libs/web-components/src/components/form-step/FormStep.svelte
libs/web-components/src/components/form-stepper/FormStepper.svelte
libs/web-components/src/components/form-stepper/form-stepper.spec.ts

fix: add @container queries to FormStepper and FormStep

---

libs/web-components/src/components/app-header/AppHeader.svelte
libs/web-components/src/components/tabs/Tabs.svelte

Critical bug fixes

---

libs/web-components/src/components/popover/Popover.svelte

Before (would not be visible)
After
Test Code
```
import { GoADropdown, GoADropdownItem } from "@abgov/react-components"
export function Bug1734Page() {
function onChange() {
// noop
}
return <>
<div style={{
height: "calc(100vh - 22rem)",
width: "100%",
display: "grid",
gridTemplateColumns: "1fr 3fr 1fr",
gridTemplateRows: "1fr 3fr 1fr",
gridTemplateAreas: `
"topleft . topright"
". center ."
"bottomleft . bottomright"
`,
}}>
<div style={{
gridArea: "topleft"
}}>
<GoADropdown name="item" onChange={onChange}>
<GoADropdownItem value="red" label="Red"></GoADropdownItem>
<GoADropdownItem value="green" label="Green"></GoADropdownItem>
<GoADropdownItem value="blue" label="Blue"></GoADropdownItem>
</GoADropdown>
</div> 
<div style={{
gridArea: "topright",
display: "flex",
justifyContent: …
```

fix(#1734): fix popover placement when displayed on the top of dropdown

---

libs/web-components/src/components/accordion/Accordion.svelte

This PR is a proposed fix for https://github.com/GovAlta/ui-components/issues/1591. It adds padding to the according heading and aligns the icon to the top. It allows the heading to accommodate multi-line heading & secondary text.
Small with one line heading:
Small with multi-line heading:
Small with one line heading and secondary text:
Small with multi-line heading and secondary text:
Small with multi-line heading and multi-line secondary text:
Medium with single line heading:
Medium with multi-line heading:
Small with single line heading
Small with multi-line heading
Medium single line heading
Medium with multi-line heading
Small with single line heading
Small with multi-line heading
Medium single line heading
Medium with multi-line heading
Small with …

fix(#1591): Add padding to accordion heading

---

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
libs/web-components/src/components/file-upload-input/file-upload-input.spec.ts

Test Code
To test the issue change the `accept=".jpg, .pdf"` portion to test file types and [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) (ex `image/*`, `image/bmp`, ...). *Note*: the `.` is required.
```
import { GoAFileUploadCard, GoAFileUploadInput, GoAFormItem } from "@abgov/react-components";
interface Uploader {
upload: (url: string | ArrayBuffer) => void;
abort: () => void;
}
interface Upload {
name: string;
file: File;
uploader: Uploader;
}
class MockUploader implements Uploader {
private processId?: any;
public onprogress: (percent: number) => void = (_: number) => { };
public onabort: () => void = () => { };
public onfail: (err: string) => void = (_: string) => { };
public oncomplete: () …
```

fix(#1763): filepicker's filetype filter when selecting files

---

libs/react-components/src/lib/date-picker/date-picker.spec.tsx
libs/react-components/src/lib/date-picker/date-picker.tsx

Fixing the issue described at [1804](https://github.com/GovAlta/ui-components/issues/1804)

fix(#1804): react datepicker calling onChange multiple times

---

libs/web-components/src/components/app-header/AppHeader.svelte
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte
libs/web-components/src/layouts/three-column-layout/ThreeColumnLayout.svelte
libs/web-components/src/layouts/two-column-layout/TwoColumnLayout.svelte

* Update padding for microsite header
* Make sure alignment between the microsite header and app header exists.
Demo link: https://vanessatran-ddi.github.io/ui-components/#/
Video: 
https://github.com/GovAlta/ui-components/assets/120135417/11361ab7-6af9-4df6-b1ef-ea2136632044

fix(#1438): update app header and microsite header padding

---

libs/web-components/src/components/form-step/FormStep.svelte
libs/web-components/src/components/form-stepper/FormStepper.svelte

https://github.com/GovAlta/ui-components/issues/1890

1890 form stepper

---

libs/react-components/src/lib/form-item/form-item.tsx

This means we need to test story #1814 again with this change

fix(#1887): Reverting error and helptext type change

---

package-lock.json
package.json

Design tokens package was 1.1.1
Design tokens package should be 1.2.0
Nothing needed to test

fix: Update Design Tokens

---

libs/web-components/src/components/text-area/TextArea.svelte

```
<goa-form-item label="Court date">
<goa-textarea goaValue [formControl]="testText" countby="character" />
```
and
```
export class TextAreaComponent {
testText = new FormControl();
}
```

fix(#1790): textarea console error

---

libs/web-components/src/components/dropdown/Dropdown.svelte

fix(#1957): date picker year selection not appearing

---

libs/web-components/src/components/tooltip/Tooltip.svelte
libs/web-components/src/components/tooltip/tooltip.spec.ts

cursor changes to a hand on hover
cursor stays the same on hover

fix(#1799): tooltip maintain mouse cursor style on hover

---

libs/web-components/src/components/radio-group/RadioGroup.spec.ts
libs/web-components/src/components/radio-group/RadioGroup.svelte
libs/web-components/src/components/radio-group/RadioGroupWrapper.test.svelte
libs/web-components/src/components/radio-item/RadioItem.spec.ts
libs/web-components/src/components/radio-item/RadioItem.svelte

Angular
```
<goa-radio-group name="item" [error]="errorVariable" mb="xl">
<goa-radio-item
value="Test 1"
label="Test 1"
/>
<goa-radio-item
value="Test 2"
label="Test 2"
/>
<goa-radio-item
value="Test 3"
label="Test 3"
/>
</goa-radio-group>
<br />
<goa-button (_click)="setError()">Set Error</goa-button>
```
React
```
const [error, setError] = React.useState<boolean>(false);
return (
<>
<GoAButton onClick={() => setError(true)}>Show Error</GoAButton>
<GoARadioGroup name="color2" value="orange" error={error} onChange={onChange}>
<GoARadioItem name="color2" value="red"></GoARadioItem>
<GoARadioItem name="color2" value="blue"></GoARadioItem>
<GoARadioItem name="color2" value="orange"></GoARadioItem>
</GoARadioGroup>
</>
)
```

1972 form item dynamic error

---

libs/web-components/src/components/app-header/AppHeader.svelte

Below 1024, the console error shows up (screenshot below)
No more console errors.

fix(#1900): fix app header console error below 1024px

---

libs/web-components/src/components/app-header/AppHeader.svelte

bug/2018: fix active links are pushed down

---

libs/web-components/src/components/app-header/AppHeader.svelte

Modify the commit message to release a hotfix #2018

fix(#2018): prettier app-header

---

libs/web-components/src/components/icon/Icon.svelte

Cannot change the icon theme
Can change it
https://jam.dev/c/6725a8af-6e2a-4f79-8a2d-239c33d6cdbe
```
<h2>Dynamic changing theme</h2>
<goa-button (_click)="changeTheme()">Change theme</goa-button>
<goa-icon type="accessibility" [theme]="iconTheme"></goa-icon>
{{ iconTheme }}
```
```
@Component({
selector: "abgov-icon",
templateUrl: "./icon.component.html"
})
export class IconComponent {
iconTheme = "outline";
constructor() {}
changeTheme() {
this.iconTheme = this.iconTheme === "filled" ? "outline" : "filled";
}
}
```

fix(#2032): change icon theme dynamically

---

libs/web-components/src/components/dropdown/Dropdown.svelte

Using our new angular component, with the filterable attribute, it takes longer to respond and search options based on the input query. 
It works as normally:
Tests passed:

fix(#1993): filterable dropdown has slow responsiveness

---

libs/react-components/src/lib/tabs/tabs.tsx
libs/web-components/src/components/tabs/Tabs.svelte
libs/web-components/src/components/tabs/tabs.spec.ts

-The _change event is available (onchange in React), returns the selected tab's index in an object `detail: { tab: _currentTab },`.
-Added a new test case
**Angular**
```
@Component({
selector: "abgov-tabs",
templateUrl: "./tabs.html",
})
export class TabsComponent {
handleTabChange(event: Event) {
const customEvent = event as CustomEvent;
const tabIndex = customEvent.detail.tab;
console.log(`Tab changed to ${tabIndex}`);
}
}
<goa-tabs (_change)="handleTabChange($event)">
<goa-tab>
<div slot="heading">Profile</div>
<p>
<b>Profile:</b> Lorem ipsum dolor sit amet.
</p>
</goa-tab>
<goa-tab>
<div slot="heading">
Review pending
<goa-badge type="important" content="1"></goa-badge>
</div>
<p>
<b>Review pending:</b> Lorem ipsum dolor sit amet, …
```

fix(#1665): tabs add onChange event

---

libs/web-components/src/components/scrollable/Scrollable.svelte

Create a modal using the actions slot, and include a form item in the content.

fix(#2012): Adding minor padding to bottom of Scrollable

---

libs/angular-components/src/lib/components/accordion/accordion.spec.ts
libs/angular-components/src/lib/components/accordion/accordion.ts
libs/angular-components/src/lib/components/callout/callout.spec.ts
libs/angular-components/src/lib/components/callout/callout.ts
libs/angular-components/src/lib/components/checkbox/checkbox.spec.ts
libs/angular-components/src/lib/components/checkbox/checkbox.ts
libs/angular-components/src/lib/components/chip/chip.spec.ts
libs/angular-components/src/lib/components/chip/chip.ts
libs/angular-components/src/lib/components/container/container.spec.ts
libs/angular-components/src/lib/components/container/container.ts
libs/angular-components/src/lib/components/details/details.spec.ts
libs/angular-components/src/lib/components/details/details.ts
libs/angular-components/src/lib/components/dropdown/dropdown.ts
libs/angular-components/src/lib/components/file-upload-input/file-upload-input.ts
libs/angular-components/src/lib/components/form-item/form-item.spec.ts
libs/angular-components/src/lib/components/form-item/form-item.ts
libs/angular-components/src/lib/components/notification-banner/notification-banner.ts
libs/angular-components/src/lib/components/pagination/pagination.ts
libs/angular-components/src/lib/components/table-sort-header/table-sort-header.ts
libs/angular-components/src/lib/components/tabs/tabs.spec.ts
libs/angular-components/src/lib/components/tabs/tabs.ts
libs/angular-components/src/lib/components/textarea/textarea.spec.ts
libs/angular-components/src/lib/components/textarea/textarea.ts
libs/common/src/lib/common.ts
libs/react-components/src/lib/pagination/pagination.spec.tsx
libs/react-components/src/lib/pagination/pagination.tsx
libs/react-components/src/lib/table/table.spec.tsx
libs/react-components/src/lib/table/table.tsx
libs/react-components/src/lib/tabs/tabs.tsx

React components are updated with some new properties and events.
* Add `maxwidth` to angular components 
* Update the way React and Angular components should handle (using `GoABXXXOnChangeDetail` instead of multiple arguments)
* Unit tests updated

chore: add maxwidth and tabs event to angular components

---

libs/web-components/src/components/side-menu/SideMenu.svelte

**Before the code change**
-Copy the code from the story#2036
-Browse to the side menu link
-And then go to any other link
-console error pops up, note the error
**Apply the code changes**
-Repeat the above steps
-should not genereate the previously noted console error

fix(#2036): side menu group console error

---

libs/react-components/src/lib/callout/callout.spec.tsx
libs/react-components/src/lib/callout/callout.tsx
libs/web-components/src/components/callout/Callout.html-data.json
libs/web-components/src/components/callout/Callout.spec.ts
libs/web-components/src/components/callout/Callout.svelte

The Callout component has aria-live property.
Angular playground sample code
```
<h1>Dynamic Callouts</h1>
<h2>Emergency Callout</h2>
<goa-callout type="emergency" heading="Emergency Update" [arialive]="emergencyAriaLive">
{{ emergencyContent }}
</goa-callout>
<h2>Important Callout</h2>
<goa-callout type="important" heading="Important Notice" [arialive]="importantAriaLive">
{{ importantContent }}
</goa-callout>
<h2>Information Callout</h2>
<goa-callout type="information" heading="Information Update" [arialive]="infoAriaLive">
{{ infoContent }}
</goa-callout>
<h2>Success Callout (Empty String aria-live)</h2>
<goa-callout type="success" heading="Success Message" [arialive]="successAriaLive">
{{ successContent }}
</goa-callout>
```
```
import { Component, OnInit } from "@angular/core"; …
```

fix(#2029): callout add aria-live property

---

_templates/react/src/main.tsx
libs/react-components/src/index.ts

React app will look like this if we don't import `@abgov/web-components`
After import it under `App.tsx`

feat(#2035): BREAKING CHANGE - remove web-components from react library

---

_templates/react/src/main.tsx
libs/react-components/src/index.ts
package-lock.json
package.json

Stories in this release:
- #2035 
This is a breaking change and will make a new release version of 5.0.0 for `react-component`

Production Release - September 11 / 2024

---

libs/angular-components/src/lib/value-directive.ts
libs/react-components/src/lib/date-picker/date-picker.spec.tsx
libs/react-components/src/lib/date-picker/date-picker.tsx
libs/web-components/src/components/date-picker/DatePicker.html-data.json
libs/web-components/src/components/date-picker/DatePicker.svelte
libs/web-components/src/components/date-picker/date-picker.spec.ts

Datepicker has no property `disabled`
Datepicker has the new property `disabled`
https://github.com/user-attachments/assets/70bbffdb-f0a3-4cbd-a5bd-2da5dbdb6421
```
import { GoAButton, GoADatePicker, GoAFormItem } from "@abgov/react-components";
export function Datepicker() {
const [value, setValue] = useState<Date>(new Date(2024, 3, 26));
const [disabled, setDisabled] = useState<boolean>(false);
function onChange(name: string, value: Date) {
console.log("onChange is triggered ", name, value);
setValue(value);
}
function toggleDisabled() {
setDisabled(!disabled);
}
return (
<>
<GoAButton mb="xl" onClick={toggleDisabled}>
Toggle Disabled State
</GoAButton>
<GoAFormItem label="Item">
<GoADatePicker
onChange={onChange}
name="item"
value={value} …
```

fix(#2044): add disabled prop to datepicker

---

libs/react-components/src/lib/date-picker/date-picker.spec.tsx
libs/react-components/src/lib/date-picker/date-picker.tsx

fix(#2000): relative prop date picker React wrapper

---

libs/react-components/src/lib/date-picker/date-picker.tsx
libs/web-components/src/components/date-picker/DatePicker.svelte
libs/web-components/src/components/date-picker/date-picker.spec.ts

The value is resetting properly.
**Angular Code**
```
import { FormControl, FormGroup, Validators } from "@angular/forms";
@Component({
selector: "abgov-datepicker",
templateUrl: "./datepicker..component.html",
styleUrls: ["./datepicker.component.css"],
})
export class DatePickerComponent {
dateCtrl = new FormControl();
setValue() {
const d = new Date();
d.setDate(d.getDate() - 7);
this.dateCtrl.patchValue(d);
console.log("setValue called: ", this.dateCtrl.value);
}
clearValue() {
this.dateCtrl.reset();
console.log("reset called: ", this.dateCtrl.value);
}
}
------------------------------
<goa-form-item label="Input Label" helptext="Helper text" mb="3xl">
<goa-date-picker [formControl]="dateCtrl" [value]="dateCtrl.value" ngDefaultControl /> …
```

fix(#2056): date picker reset issues (React fix)

---

libs/react-components/src/lib/microsite-header/microsite-header.tsx
libs/web-components/src/components/microsite-header/MicrositeHeader.spec.ts
libs/web-components/src/components/microsite-header/MicrositeHeader.svelte

**Playground Angular Code**
Template
```
<h1>Microsite Header</h1>
<h2>Feedback Url Provided (open new window)</h2>
<goa-microsite-header
type="alpha"
version="v1.2.3"
feedbackurl="https://www.yahoo.com"
></goa-microsite-header>
<h2>Feedback with Click Handler</h2>
<goa-microsite-header
type="beta"
version="v1.2.3"
[hasfeedbackhandler]="true"
(_feedbackClick)="handleFeedbackClick($event)"
></goa-microsite-header>
<h2>Feedback hidden (b/c no url no click event)</h2>
<goa-microsite-header
type="beta"
version="v1.2.3"
></goa-microsite-header>
```
Typescript
```
@Component({
selector: "abgov-microsite-header",
templateUrl: "./microsite-header.component.html",
})
export class MicrositeHeaderComponent {
constructor() {}
handleFeedbackClick(event: …
```

fix(#1897): microsite header add feedback click handler

---

libs/web-components/src/components/date-picker/DatePicker.svelte

fix: remove duplicate testid in datepicker

---

libs/angular-components/src/index.ts
libs/angular-components/src/lib/validation.spec.ts
libs/angular-components/src/lib/validation.ts

fix: add angular validation

---

libs/angular-components/src/index.ts
libs/angular-components/src/lib/checked-directive.ts
libs/angular-components/src/lib/validation.spec.ts
libs/angular-components/src/lib/validation.ts
libs/react-components/src/experimental/resizable-panel/ResizablePanel.tsx
libs/web-components/src/common/no-scroll.ts
libs/web-components/src/components/tooltip/Tooltip.svelte

This is being done so fast after the last Production PR, because the last PR didn't actually update any of the existing releases. Hopefully this remedies that problem.

Production Release - September 26 / 2024

---

libs/web-components/src/components/button-group/ButtonGroup.svelte

-Test code examples below with and without button group
**Angular Test Code**
```
<h2>Using Button Group</h2>
<goa-button-group>
<goa-button type="primary" size="compact" (_click)="onClick()">
Button
</goa-button>
<goa-button type="primary" size="compact" leadingicon="arrow-forward" (_click)="onClick()">
Button
</goa-button>
<goa-button type="primary" size="compact" trailingicon="arrow-forward" (_click)="onClick()">
Button
</goa-button>
</goa-button-group>
<h2>Without button group (inside a div)</h2>
<div style="display: flex;">
<goa-button type="primary" size="compact" (_click)="onClick()" mr="xs">
Button
</goa-button>
<goa-button type="primary" size="compact" leadingicon="arrow-forward" (_click)="onClick()"  ml="xs" mr="xs">
Button
</goa-button>
<goa-button type="primary" size="compact" …
```

fix(#2103): button group leading Icon is out of alignment

---

libs/web-components/src/components/form/Fieldset.svelte

add missing message handler

---

libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/popover/Popover.svelte

Playground Test Code
Width specified
```
export default function Dropdown() {
return (
<GoAFormItem label="Dropdown" requirement="optional">
<GoADropdown
name="dropdown"
width="30ch"
placeholder="Select a value"
onChange={function (name: string, values: string[] | string): void {
throw new Error("Function not implemented. ");
}}
>
<GoADropdownItem key="_none_" name="none" value="" label="None" />
<GoADropdownItem key="_some_" name="some" value="" label="Some Long Value Some Long Value" />
</GoADropdown>
</GoAFormItem>
);
}
```
No width specified
```
export default function Dropdown() {
return (
<GoAFormItem label="Dropdown" requirement="optional">
<GoADropdown
name="dropdown"
placeholder="Select a value"
onChange={function (name: string, values: string[] | string): void {
throw new …
```

fix(#2108): dropdown width related issues

---

libs/web-components/src/components/side-menu/SideMenu.svelte
libs/web-components/src/components/side-menu/side-menu.spec.ts

fix(#1973): side menu active link issues

---

libs/react-components/package.exp.json
libs/react-components/package.json
libs/react-components/project.json
libs/react-components/src/experimental/index.ts
libs/react-components/src/lib/drawer/drawer.spec.tsx
libs/react-components/src/lib/drawer/drawer.tsx
libs/react-components/tsconfig.exp.json
libs/react-components/vite.config.ts
libs/web-components/src/common/no-scroll.ts
libs/web-components/src/common/types.ts
libs/web-components/src/common/utils.ts
libs/web-components/src/components/drawer/Drawer.svelte
libs/web-components/src/components/drawer/DrawerWrapper.test.svelte
libs/web-components/src/components/drawer/drawer.spec.ts
libs/web-components/src/index.ts
package-lock.json
package.json
tsconfig.base.json

```
import { GoADrawer } from "@abgov/react-components";
export function Drawer() {
const [open, setOpen] = useState<boolean>(false);
function toggleOpen() {
setOpen(!open)      ;
}
return (
<>
<button onClick={toggleOpen}>Show</button>
<GoADrawer open={open} position="left" maxSize="400px" onClose={toggleOpen}>
<div style={{margin: "50rem 0"}}>
content
</div>
</GoADrawer>
</>
)
}
export default Drawer;
```
```
<goa-button (_click)="toggleDrawer()">Menu</goa-button>
<goa-drawer [open]="showDrawer" (_close)="toggleDrawer()" position="left" maxsize="400px" heading="Menu">
<goa-accordion heading="Heading" headingsize="medium">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim …
```

feat: drawer component

---

libs/react-components/src/index.ts
libs/react-components/src/lib/filter-chip/filter-chip.spec.tsx
libs/react-components/src/lib/filter-chip/filter-chip.tsx
libs/web-components/src/components/chip/Chip.svelte
libs/web-components/src/components/filter-chip/FilterChip.html-data.json
libs/web-components/src/components/filter-chip/FilterChip.spec.ts
libs/web-components/src/components/filter-chip/FilterChip.svelte
libs/web-components/src/components/filter-chip/doc.md
libs/web-components/src/index.ts

A separate PR for the documentation update is also needed.
**Playground Angular Example**
Typescript
```
@Component({
selector: "abgov-chip",
templateUrl: "./filter-chip.component.html",
styleUrl: "./filter-chip.component.css",
})
export class FilterChipComponent {
chips: string[] = ["Chip 1", "Chip 2", "Chip 3"];
activeFilters: string[] = [];
typedChips: string[] = ["Typed Chip 1", "Typed Chip 2", "Typed Chip 3"];
inputValue = "";
deleteChip(chip: string): void {
this.chips = this.chips.filter((c) => c !== chip);
}
onClick(): void {
console.log("Chip clicked");
}
```
Html
```
<h1>Filter Chip</h1>
<h2>Delete event</h2>
<goa-filter-chip
*ngFor="let chip of chips"
[content]="chip"
(_click)="deleteChip(chip)"
mr="s"
></goa-filter-chip>
<h2>Error …
```

fix(#1943): new component filterchip

---

libs/web-components/src/components/calendar/Calendar.svelte

fix(#2171): calendar not updating when set programatically

---

libs/react-components/src/lib/dropdown/dropdown-item.tsx
libs/web-components/src/common/utils.ts
libs/web-components/src/components/accordion/Accordion.svelte
libs/web-components/src/components/container/Container.svelte
libs/web-components/src/components/dropdown/Dropdown.spec.ts
libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/dropdown/DropdownItem.svelte
libs/web-components/src/components/tabs/Tabs.svelte

Angular
```
coming soon
```
React
```
const [colors, setColors] = useState<string[]>([]);
const [data, setData] = useState<string>("");
const [tabData, setTabData] = useState<{heading: string, content: string}[]>([]);
useEffect(() => {
setTimeout(() => {
setColors(["red", "blue", "green"]);
setData("Hello")
setTabData([
{heading: "Tab 1", content: "Tab 1 content"},
{heading: "Tab 2", content: "Tab 2 content"},
])
}, 2000)
}, []);
function changeColors() {
console.log("change colors")
setColors(["yellow", "purple", "red"]);
}
function onChange(name: string, value: string | string[]) {
// nothing  
}
```
```
<GoADropdown name="item" value="" onChange={onChange} native={true}>
{colors.map(color =>
<GoADropdownItem key={color} value={color} label={color}></GoADropdownItem>
)}
</GoADropdown> …
```

2277 dynamic children

---

.github/workflows/alpha-release-ci.yml
.github/workflows/prod-release-ci.yml
package.json

fix: release workflow - update release workflow for major release

---

libs/common/package.json
libs/common/src/lib/common.ts

fix(#2991): make ui-components-common package to be public

---

libs/web-components/src/components/text-area/TextArea.svelte

fix(#2200): textarea width issues

---

libs/common/src/lib/public-form-controller.spec.ts
libs/common/src/lib/public-form-controller.ts
libs/common/src/lib/validation.spec.ts
libs/web-components/src/components/date-picker/DatePicker.svelte
libs/web-components/src/components/form/Fieldset.svelte
libs/web-components/src/components/form/Form.svelte
libs/web-components/src/components/form/FormPage.svelte
libs/web-components/src/components/form/FormSummary.svelte
libs/web-components/src/components/form/SubForm.svelte
libs/web-components/src/components/form/SubFormIndex.svelte
libs/web-components/src/types/relay-types.ts

The last commit includes a fix to the datepicker, in it not changing when the value it is bound to changes. This issue can be tested with the following 
Angular only
```ts
someDate = "2024-06-12";
resetDate() {
this.someDate = "2026-02-13";
}
onDateChange(e: Event) {
this.someDate = (e as CustomEvent).detail.value;
}
```
```
<goab-block direction="row" alignment="center">
<goa-date-picker type="input" [value]="someDate" (_change)="onDateChange($event)"></goa-date-picker>
<goa-link-button (_click)="resetDate()">Reset date</goa-link-button>
</goab-block>
```
Before
[Screencast from 2025-02-12 14-28-35.webm](https://github.com/user-attachments/assets/82e925b1-57e3-436e-b5f6-7fbc10202776)
After
[Screencast from 2025-02-12 14-27-25.webm](https://github.com/user-attachments/assets/9382f82c-5021- …

Public form fixes

---

libs/angular-components/src/lib/components/input/input.ts
libs/react-components/src/lib/input/input.tsx
libs/web-components/src/components/input/Input.svelte

`<goab-input name="foo" trailingIcon="finger-print" trailingIconAriaLabel="Authenticate with fingerprint"></goab-input>`
Video attached with NVDA screen reader results.

fix(#2332): input aria label prop for trailing-icon

---

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte

```
<h1>File Upload</h1>
<goa-file-upload-input
[accept]="acceptedTypes"
(_selectFile)="uploadFile($event)"
></goa-file-upload-input>
<goa-file-upload-card
*ngFor="let upload of uploads; index as i"
[type]="upload.file.type"
[size]="upload.file.size"
[filename]="upload.file.name"
[progress]="progressList[upload.file.name]"
(_delete)="deleteFile(upload)"
(_cancel)="deleteFile(upload)"
>
</goa-file-upload-card>
```
```
interface Uploader {
upload: (url: string | ArrayBuffer) => void;
abort: () => void;
}
interface Upload {
file: File;
uploader: Uploader;
}
class MockUploader implements Uploader {
public onprogress: (percent: number) => void = (_: number) => {};
public onabort: () => void = () => {};
public onfail: (err: string) => void = (_: …
```

fix(#1850): fileuploadinput accept property issue

---

libs/web-components/src/components/footer-meta-section/FooterMetaSection.svelte

```
<goab-app-footer maxContentWidth="var(--footer-width-max)">
<goab-app-footer-meta-section slot="meta">
<a href="/button" target="_blank" (click)="handleClickLink($event)">Goto Button</a>
</goab-app-footer-meta-section>
</goab-app-footer>
```
```
import {
GoabAppFooter,
GoabAppFooterMetaSection,
GoabAppFooterNavSection
} from "@abgov/angular-components";
@Component({
selector: "abgov-app-footer",
standalone: true,
imports: [
GoabAppFooter,
GoabAppFooterNavSection,
GoabAppFooterMetaSection,
],
templateUrl: './app-footer.component.html'
})
export class AppFooterComponent {
handleClickLink(event: Event): void {
console.log(">>> handleClickLink is called.");
event.preventDefault();
}
}
```

fix(#2013): app footer click event and target issue

---

libs/angular-components/src/lib/components/date-picker/date-picker.spec.ts
libs/angular-components/src/lib/components/date-picker/date-picker.ts

https://github.com/user-attachments/assets/412860e3-616c-4a2e-b834-0ed0cb4582d9
Angular Playground Test Code
```
<h2>Reactive form</h2>
<form [formGroup]="form">
<p>Selected Date: {{ form.get('datePicker')?.value }}</p>
<goab-date-picker formControlName="datePicker" name="date-picker"></goab-date-picker>
</form>
<goab-button (onClick)="currentValueReactive()">Console Log (Reactive Form)</goab-button>
<goab-button (onClick)="resetDatePickerReactive()">Reset (Reactive Form)</goab-button>
```
```
@Component({
standalone: true,
selector: "abgov-date-picker",
templateUrl: "./date-picker.component.html",
imports: [GoabDatePicker, GoabFormItem, FormsModule, ReactiveFormsModule, GoabButton],
})
export class DatePickerComponent {
disabled = false;
dateControl = new FormControl<Date | …
```

fix(#2154): datepicker reset UI value angular wrapper

---

libs/web-components/src/components/checkbox/Checkbox.svelte
libs/web-components/src/components/date-picker/DatePicker.svelte
libs/web-components/src/components/dropdown/Dropdown.svelte
libs/web-components/src/components/form/Fieldset.svelte
libs/web-components/src/components/form/FormPage.svelte
libs/web-components/src/components/input/Input.svelte
libs/web-components/src/components/radio-group/RadioGroup.svelte
libs/web-components/src/components/text-area/TextArea.svelte
libs/web-components/src/types/relay-types.ts

Small changes were made to some of the non-public-form components, but other than the TextArea, the changes would not affect how things currently work. The TextArea has a small refactor, therefore should be tested.

Public form updates

---

libs/web-components/src/components/calendar/Calendar.svelte
libs/web-components/src/components/calendar/calendar.spec.ts

https://github.com/user-attachments/assets/37046c94-0def-47cb-92b0-859fafa9fcc3

fix(#2407): datepicker can't set min and max dynamically

---

libs/web-components/src/common/urls.ts

https://github.com/user-attachments/assets/1b4fd831-31c4-4018-8f2a-c9cc11a00f08

fix(#2345): appheader links with query strings not showing as active

---

libs/web-components/src/components/filter-chip/FilterChip.svelte

fix(#2315): filter chip incorrect spacing and size of icon

---

libs/web-components/src/components/badge/Badge.svelte

fix(#2388): badge console error issue

---

libs/web-components/src/components/form-item/FormItem.svelte

fix(#2424): helper text displaying at bottom on page

---

.github/CODEOWNERS

Nothing to test, this just adds @BumbleB2na to the Codeowners and removes myself.

chore: Updated CODEOWNERS file

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Nothing can be tested here, but @Spark450 should test the Bug Report and Feature Request forms via New Issue after it's pushed

chore(#2504): Updated Github bug and feature forms

---

libs/react-components/src/lib/button/button.spec.tsx
libs/react-components/src/lib/button/button.tsx

https://github.com/user-attachments/assets/62390659-81b6-470e-812e-bbe105beeef6
https://github.com/user-attachments/assets/3c3db54f-46a8-4943-887f-04274beef9f3

fix(#2384): button rendered with disabled=false react

---

libs/react-components/src/lib/button/button.spec.tsx
libs/react-components/src/lib/button/button.tsx

fix(#2384): (LTS) button rendered with disabled=false react 

---

libs/web-components/src/components/input/Input.svelte
package-lock.json
package.json

This video demonstrates both the before and after, where the "after" is denoted by a thin blue border on the left side:
<video src="https://github.com/user-attachments/assets/6685986d-56f0-412e-a912-ac01f9cf0e5d" width="200"></video>
Leading/trailing content elements were moved up to parent element to support the change needed in this story.
- Fixed disabled state: There was a `border` around disabled input making the input slightly larger when in disabled state. The `border` has been changed to `box-shadow` just like used for all other input states. This is demonstrated in the video.
```svelte
<script lang="ts">
</script>
<h2>Additional Tests</h2>
<goa-form-item label="Two side-by-side text input with 10ch width">
<goa-input
name="name1"
type="text"
value=""
width="10ch"
></goa-input> …
```

fix(#2350): input state with leading and trailing content

---

.github/workflows/alpha-release-ci.yml
.github/workflows/lts-release-ci.yml
.github/workflows/prod-release-ci.yml
.github/workflows/pull-request.yml

chore(#2556): sync the lts github workflow files to the alpha branch

---

.github/workflows/pull-request.yml

fix(#2556): fix action files again

---

package.json

chore(#2556): fix build

---

package.json

chore: point the lts build to the lts base

---

libs/web-components/src/experimental/ExperimentalFormStepper.svelte

Minimum width was 180 px
Minimum width has been changed to 108px

Change min-width of step to 108px

---

libs/web-components/src/components/dropdown/Dropdown.spec.ts
libs/web-components/src/components/dropdown/Dropdown.svelte

fix(#2355): dropdown chevron unusable tab order

---

libs/angular-components/src/lib/components/badge/badge.ts
package.json

To compare I had 2 components (new and old angular)
```
<goab-container padding="compact">
<div class="card-header">
<div class="body-l"><a href="#">1234ABC</a></div>
<goab-badge type="information" content="Draft"></goab-badge>
</div>
<div class="card-header">
<div class="body-l"><a href="#">1234ABC</a></div>
<goa-badge type="information" content="old angular"></goa-badge>
</div>
</goab-container>
```
```
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
import { GoabBadge, GoabContainer } from "@abgov/angular-components";
@Component({
selector: "abgov-issue-2513",
templateUrl: "./issue-2513.component.html",
styleUrls: ["./issue-2513.component.css"],
standalone: true,
imports: [
GoabContainer,
GoabBadge
],
schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class …
```

fix(#2513): goab-badge is out of alignment

---

libs/react-components/specs/tabs.browser.spec.tsx
libs/web-components/src/components/tabs/Tabs.svelte
libs/web-components/src/components/tabs/tabs.spec.ts

1. Tabs component creates duplicate history entries, requiring two back-button clicks to return
2. URL and tab selection behavior issues:
- Tab URLs are automatically added on page load without user interaction
- Page automatically scrolls to tabs on load when using hash navigatio
- Anchor links within tabs don't work as they're overridden by tab navigation. Example: Loading `/page#toc-3` gets overwritten to `/page#tab-0`
3. `initialTab` doesn't do anything #2471  because right now href hash overrides it. 
1. Improved history management: Back button properly returns to previous page
2. Better URL handling:
- Tab hash (#tab-X) only added when user explicitly selects a tab (or `initialTab` is defined)
- No automatic scrolling to tabs on initial page load
- Anchor links within tabs are …

fix(#2433): tabs url issues

---

libs/react-components/specs/dropdown.browser.spec.tsx
libs/web-components/src/components/dropdown/Dropdown.svelte

Issue 1: 
Resize the browser the pop-over for dropdown isn't aligned. 
Issue 2: It seems to be fixed by https://github.com/GovAlta/ui-components/issues/2466
https://github.com/user-attachments/assets/a0f39f72-c582-4a4d-94ca-e8861db62d64
Code below to test both 2 issues 
Angular code: 
```
<p> Issue: If you resize the browser, the popover of the dropdown will be bigger and not fit into the dropdown's input width.</p>
<p> Issue: If you make the dropdown at the bottom, popover should be above the dropdown but now it is at the below</p>
<div style="height: 500px"></div>
<div style="margin-bottom:30px">
<goab-form-item label="Country">
<goab-dropdown
name="genderId"
width="100%"
placeholder="--Select Country--"
formControlName="countryDropdown"
>
<goab-dropdown-item value="null" …
```

fix(#2441): popover max width should be equal with dropdown width

---

libs/web-components/src/components/input/Input.svelte

-For text overflow, the 3 dots show up (This was already confirmed with Tom, refer to the #2438 )
-when mouse is hovered the 'x' shows up for Search.
**Angular Code**
```
<h1>Ticket #2409</h1>
<h1>% based</h1>
<goab-form-item label="50% width">
<goab-input
name="name7"
type="text"
value=""
width="50%"
></goab-input>
<goab-form-item label="50% width + leading icon">
<goab-input
name="name12"
type="text"
value=""
width="50%"
leadingIcon="arrow-back"
>
</goab-input>
<goab-form-item label="50% width + trailing icon">
<goab-input
name="name12"
type="text"
value=""
width="50%"
trailingIcon="arrow-forward"
>
</goab-input>
<goab-form-item label="50% width, leading/trailing icons">
<goab-input
name="name8"
type="text"
value=""
width="50%" …
```

fix(#2409): input width property inconsistencies

---

libs/web-components/src/components/hero-banner/HeroBanner.spec.ts
libs/web-components/src/components/hero-banner/HeroBanner.svelte

fix(#2696): replace h1 with goa-text in hero banner

---

libs/angular-components/src/lib/components/accordion/accordion.ts
libs/angular-components/src/lib/components/badge/badge.ts
libs/angular-components/src/lib/components/base.component.ts
libs/angular-components/src/lib/components/button/button.ts
libs/angular-components/src/lib/components/card/card.ts
libs/angular-components/src/lib/components/checkbox/checkbox.ts
libs/angular-components/src/lib/components/chip/chip.ts
libs/angular-components/src/lib/components/circular-progress/circular-progress.ts
libs/angular-components/src/lib/components/details/details.ts
libs/angular-components/src/lib/components/drawer/drawer.ts
libs/angular-components/src/lib/components/dropdown/dropdown.ts
libs/angular-components/src/lib/components/file-upload-card/file-upload-card.ts
libs/angular-components/src/lib/components/filter-chip/filter-chip.ts
libs/angular-components/src/lib/components/header/header.ts
libs/angular-components/src/lib/components/icon-button/icon-button.ts
libs/angular-components/src/lib/components/icon/icon.ts
libs/angular-components/src/lib/components/input-number/input-number.ts
libs/angular-components/src/lib/components/input/input.ts
libs/angular-components/src/lib/components/modal/modal.ts
libs/angular-components/src/lib/components/pages/pages.ts
libs/angular-components/src/lib/components/radio-item/radio-item.ts
libs/angular-components/src/lib/components/skeleton/skeleton.ts
libs/angular-components/src/lib/components/spinner/spinner.ts
libs/angular-components/src/lib/components/tabs/tabs.ts
libs/angular-components/src/lib/components/textarea/textarea.ts

```
<goab-form-item>
<goab-textarea
name="reasonText"
formControlName="reasonText"
[rows]="3"
[maxCount]="256"
></goab-textarea>
```
rows and maxCount can be set as strings
```
<goab-form-item>
<goab-textarea
name="reasonText"
formControlName="reasonText"
rows="3"
maxCount="256"
></goab-textarea>
```

introduced transform: booleanAttribute and transform: numberAttribute

---

libs/react-components/src/lib/text/text.spec.tsx
libs/react-components/src/lib/text/text.tsx

fix: force version bump

---

libs/web-components/src/components/file-upload-input/FileUploadInput.svelte
libs/web-components/src/components/file-upload-input/file-upload-input.spec.ts

```
<goab-file-upload-input accept=".PDF" variant="dragdrop" maxFileSize="10MB"
(onSelectFile)="uploadFile($event)" />
<goab-file-upload-card *ngFor="let upload of uploads; index as i" [type]="upload.file.type" [size]="upload.file.size"
[filename]="upload.file.name" [progress]="progressList[upload.file.name]" (onDelete)="deleteFile(upload)"
(onCancel)="deleteFile(upload)">
</goab-file-upload-card>
```

fix(#1849): fileUploadInput "accept" property case-insensitive

---

libs/web-components/src/components/pagination/Pagination.svelte
libs/web-components/src/components/pagination/pagination.spec.ts

This PR resolves following
-https://github.com/GovAlta/ui-components/issues/2348 
-https://github.com/GovAlta/ui-components/issues/2395

fix(#2395): pagination change event fires twice + fix(#2348): pagination Page x of 0 when no content is displayed

---

libs/angular-components/src/lib/components/input-number/input-number.spec.ts
libs/angular-components/src/lib/components/input-number/input-number.ts
libs/angular-components/src/lib/components/input/input.spec.ts
libs/angular-components/src/lib/components/input/input.ts
libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx
libs/web-components/src/components/input/Input.spec.ts
libs/web-components/src/components/input/Input.svelte

fix(#2722): add text-align option to goab-input

---

libs/react-components/src/lib/input/input.spec.tsx
libs/react-components/src/lib/input/input.tsx

fix(#2722): LTS - add text-align option to goa-input

---

libs/web-components/src/components/text-area/TextArea.svelte

fix(#2542): textarea background

---

libs/angular-components/src/lib/components/input/input.ts

fix(#2404): input angular icon button issue

---

libs/react-components/src/lib/file-upload-card/file-upload-card.spec.tsx
libs/react-components/src/lib/file-upload-card/file-upload-card.tsx

fix(#2459): react file upload card make testId optional

---

libs/react-components/specs/tabs.browser.spec.tsx
libs/web-components/src/components/tabs/Tabs.svelte

```
<goab-tabs [initialTab]="1" (onChange)="tabsOnChange($event)">
<goab-tab heading="Vanessa space">
Tab Item 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</goab-tab>
<goab-tab heading="Dustin space">
Tab Item 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
<p>
<a href="javascript:void(0)" (click)="goToTab(2)" style="color: #0066cc; text-decoration: underline; cursor: pointer;">
Go back to Tab 1 (Vanessa space)
</a>
</p>
</goab-tab>
<goab-tab heading="Chris space">
Tab Item 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
<div style="height: …
```

fix(#2720): change the loaded tab via a link on the same page

---

libs/common/src/lib/common.ts
libs/web-components/src/components/form/Fieldset.svelte
libs/web-components/src/components/form/FormSummary.svelte
libs/web-components/src/components/radio-group/RadioGroup.svelte
libs/web-components/src/components/radio-item/RadioItem.spec.ts
libs/web-components/src/components/radio-item/RadioItem.svelte

When we have this code for Public form:
```
<GoabPublicFormPage id="how-long-in-alberta" heading="How long have you been living in Alberta?" buttonText={"Save and continue"} onContinue={(e) => onContinue(e, "how-long-in-alberta")}>
<GoabFieldset>
<GoabFormItem name="Years in Alberta">
<GoabRadioGroup name={"how-long-in-alberta"} id="how-long-in-alberta">
<GoabRadioItem value="less" label="Less than 1 year"></GoabRadioItem>
<GoabRadioItem value="greater" label="Greater than 1 year"></GoabRadioItem>
</GoabRadioGroup>
</GoabFormItem>
</GoabFieldset>
</GoabPublicFormPage>
```
The state initialize like this: 
Therefore at the summary page we have:
Complete state will be like this:
Angular code:
```
<h1>Public Form Radio Label Example</h1>
<goab-public-form
name="radio-label-form" …
```

fix(#2810): allow public form summary displays selected radio option's label

---

libs/web-components/src/components/input/Input.svelte

Resolves: [2782](https://github.com/GovAlta/ui-components/issues/2782)
Fixes z-index layering of children
React:
```tsx
import { GoabBlock, GoabFormItem, GoabInput, GoabText } from "@abgov/react-components";
export function InputDisabledContainerRoute() {
return (
<main>
<GoabBlock direction="column" mb="m">
<GoabText>Inputs:</GoabText>
<GoabFormItem>
<GoabInput
name="input"
value="test"
/>
</GoabFormItem>
<GoabFormItem>
<GoabInput
name="inputIcons"
value="test"
leadingIcon="bag"
trailingIcon="bag"
leadingContent="content"
trailingContent="content"
/>
</GoabFormItem>
<GoabFormItem>
<GoabInput
name="inputDisabled"
disabled
value="test"
/>
</GoabFormItem>
<GoabFormItem>
<GoabInput
name="inputDisabledIcons"
disabled
value="test"
leadingIcon="bag"
trailingIcon="bag"
leadingContent="content" …
```

fix(#2782): input z-index stacking base layer

---

libs/angular-components/src/lib/components/index.ts
libs/angular-components/src/lib/components/temporary-notification-ctrl/temporary-notification-ctrl.spec.ts
libs/angular-components/src/lib/components/temporary-notification-ctrl/temporary-notification-ctrl.ts
libs/angular-components/src/lib/components/temporary-notification/temporary-notification.spec.ts
libs/angular-components/src/lib/components/temporary-notification/temporary-notification.ts
libs/common/src/index.ts
libs/common/src/lib/messaging/messaging.ts
libs/common/src/lib/public-form-controller.ts
libs/common/src/lib/temporary-notification-controller/temporary-notification-controller.ts
libs/react-components/specs/accordion.browser.spec.tsx
libs/react-components/specs/popover.browser.spec.tsx
libs/react-components/specs/tabs.browser.spec.tsx
libs/react-components/specs/temporary-notification-ctrl.browser.spec.tsx
libs/react-components/src/index.ts
libs/react-components/src/lib/temporary-notification-ctrl/temporary-notification-ctrl.spec.tsx
libs/react-components/src/lib/temporary-notification-ctrl/temporary-notification-ctrl.tsx
libs/react-components/src/lib/temporary-notification/temporary-notification.spec.tsx
libs/react-components/src/lib/temporary-notification/temporary-notification.tsx
libs/web-components/src/common/utils.ts
libs/web-components/src/components/link-button/LinkButton.svelte
libs/web-components/src/components/link/Link.svelte
libs/web-components/src/components/popover/Popover.svelte
libs/web-components/src/components/temporary-notification/TemporaryNotification.spec.ts
libs/web-components/src/components/temporary-notification/TemporaryNotification.svelte
libs/web-components/src/components/temporary-notification/TemporaryNotificationCtrl.svelte
libs/web-components/src/index.ts

```typescript
import {
GoabBlock,
GoabButton,
GoabTemporaryNotificationCtrl,
} from "@abgov/react-components";
import { sendTemporaryNotification, sendTemporaryNotificationProgress } from "@abgov/ui-components-common";
import {
TemporaryNotification
} from "@abgov/ui-components-common";
export function TestContent() {
function sendCancellableNotification(message: string) {
const uuid = TemporaryNotification.show(message, {
actionText: "Cancel",
action: () => TemporaryNotification.show("Cancelled", { cancelUUID: uuid, duration: TemporaryNotificationShortDuration }),
})
}
function sendCancellableNotification2(message: string) {
const uuid = TemporaryNotification.show(message, {
actionText: "Undo",
duration: "medium",
action: () => …
```

feat(#2730): add new TemporaryNotification component and controller

---

libs/angular-components/src/lib/components/form/fieldset.spec.ts
libs/angular-components/src/lib/components/form/fieldset.ts
libs/angular-components/src/lib/components/form/public-form-page.spec.ts
libs/angular-components/src/lib/components/form/public-form-page.ts
libs/angular-components/src/lib/components/form/task-list.ts
libs/common/src/lib/common.ts
libs/react-components/src/lib/form/fieldset.spec.tsx
libs/react-components/src/lib/form/fieldset.tsx
libs/react-components/src/lib/form/public-form-page.spec.tsx
libs/react-components/src/lib/form/public-form-page.tsx
libs/react-components/src/lib/form/task-list.tsx
libs/react-components/src/lib/form/task.tsx

fix(#2805): remove mis-aligned properties public form components

---

libs/angular-components/src/lib/components/modal/modal.ts
libs/react-components/specs/modal.browser.spec.tsx
libs/react-components/src/lib/modal/modal.spec.tsx
libs/react-components/src/lib/modal/modal.tsx
libs/web-components/src/components/modal/Modal.spec.ts
libs/web-components/src/components/modal/Modal.svelte

Before: https://stackblitz.com/~/github.com/vanessatran-ddi/ui-components-react-sandbox/tree/prod/2410-verify?file=src/App.tsx 
If the modal has a content too long and the modal has a role "alertdialog", when opening the modal, the modal will scroll to the first focusable element which is a link. We expect the scrolling remains the same (not scrolling)
We remove the `role`:
And when we open a long content: 
It will not scroll down, and when we tab to move to the next focusable element, it will scroll down to the link at the bottom. 
Example code:
```
<h2>Issue #2829: Modal AlertDialog Focus and Screen Reader Fix</h2>
<p><strong>Problem:</strong> When role="alertdialog" is used, opening the modal automatically scrolled to the "Wholesale trade" link, hiding the full modal content. After …
```

fix(#2829): not autofocus and scroll when modal is alertdialog

---

libs/react-components/specs/radio.browser.spec.tsx
libs/web-components/src/components/radio-item/RadioItem.spec.ts
libs/web-components/src/components/radio-item/RadioItem.svelte

- [] I have tested the functionality in both React and Angular.

chore: use vitest locators within radioitem tests

---

libs/angular-components/src/lib/components/tooltip/tooltip.ts
libs/react-components/specs/tooltip.browser.spec.tsx
libs/react-components/src/lib/tooltip/tooltip.tsx
libs/web-components/src/components/tooltip/Tooltip.svelte

**Angular Playground Code**
```
<h2>Tooltip</h2>
<section style="margin-bottom: 40px; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
<h3 style="margin-top: 0; margin-bottom: 16px; color: #333;">String Content (Backward Compatible)</h3>
<div style="display: flex; align-items: center; gap: 16px; margin-bottom: 12px;">
<goab-tooltip content="Trying some more long form text here to see how it's rendered">
<goab-icon type="information-circle" />
</goab-tooltip>
<span>Hover over the icon for simple text</span>
</div>
<div style="display: flex; align-items: center; gap: 16px; margin-bottom: 12px;">
<goab-tooltip [content]="randomValue">
<goab-icon type="information-circle" />
</goab-tooltip>
<span>Dynamic string content example</span>
</div>
</section>
<section …
```

fix(#1547): allow multiline tooltip and slot

---

libs/web-components/src/common/utils.spec.ts
libs/web-components/src/common/utils.ts

This helper function should be used within #2664

chore: add helper function to for use within datepicker

---

libs/react-components/specs/dropdown.browser.spec.tsx
libs/react-components/specs/temporary-notification-ctrl.browser.spec.tsx

chore: fix the often failing browser tests
